/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.After;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class LoggingTest {
    private static final String ESC = String.valueOf((char) 27);
    private static final String RESET = ESC + "[0m";
    private static final String GREEN = ESC + "[32m";
    private static final String YELLOW = ESC + "[33m";
    private static final String RED = ESC + "[31m";
    private static final String BLUE = ESC + "[34m";

    private static final String NL = System.lineSeparator();

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    // ---------------------------------------------------------------------
    // Test doubles.
    //
    // Logging hands the level and the message to the formatter and prints
    // whatever string comes back, so recording the arguments here is what
    // makes the level and the message assertable, and the returned string is
    // what should turn up at the destination.
    // ---------------------------------------------------------------------

    private record Call(LogLevel level, String message, List<Object> args) {
        String rendered() {
            return LogLevel.color(level) + "[" + level + "] " + message + RESET;
        }
    }

    private static final class RecordingFormatter implements Formatable {
        private final List<Call> calls = new ArrayList<>();

        @Override
        public String getFormattedString(LogLevel level, String message, Object... args) {
            var call = new Call(level, message, Arrays.asList(args));
            calls.add(call);
            return call.rendered();
        }

        Call only() {
            assertEquals("expected exactly one formatted line", 1, calls.size());
            return calls.get(0);
        }
    }

    /** Throws on its first call only, so the logger's recovery path can format. */
    private static final class FailsOnceFormatter implements Formatable {
        private final List<Call> calls = new ArrayList<>();
        private boolean armed = true;

        @Override
        public String getFormattedString(LogLevel level, String message, Object... args) {
            if (armed) {
                armed = false;
                throw new IllegalStateException("formatter exploded");
            }
            var call = new Call(level, message, Arrays.asList(args));
            calls.add(call);
            return call.rendered();
        }
    }

    private static final class AlwaysFailsFormatter implements Formatable {
        @Override
        public String getFormattedString(LogLevel level, String message, Object... args) {
            throw new IllegalStateException("formatter exploded");
        }
    }

    // ---------------------------------------------------------------------
    // Standard streams are redirected for every test, so a logger built with
    // the default destination writes somewhere we can read back.
    // ---------------------------------------------------------------------

    private final PrintStream realStdout = System.out;
    private final PrintStream realStderr = System.err;

    private ByteArrayOutputStream stdout;
    private ByteArrayOutputStream stderr;

    @Before
    public void redirectStandardStreams() {
        stdout = new ByteArrayOutputStream();
        stderr = new ByteArrayOutputStream();
        System.setOut(new PrintStream(stdout, true, StandardCharsets.UTF_8));
        System.setErr(new PrintStream(stderr, true, StandardCharsets.UTF_8));
    }

    @After
    public void restoreStandardStreams() {
        System.setOut(realStdout);
        System.setErr(realStderr);
    }

    private String stdoutText() {
        return stdout.toString(StandardCharsets.UTF_8);
    }

    private String stderrText() {
        return stderr.toString(StandardCharsets.UTF_8);
    }

    private static LogOptions to(LogDestination destination) {
        return LogOptions.initiateOptions().setDestination(destination);
    }

    /** Logging only publishes the two-argument factory, so tests go through this. */
    private static Loggable logger(Formatable formatter) {
        return Logging.getLogger(formatter, LogOptions.initiateOptions());
    }

    // ---------------------------------------------------------------------
    // What each level hands to the formatter.
    // ---------------------------------------------------------------------

    @Test
    public void infoIsFormattedAtInfoAndCarriesTheMessage() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("Hello, World!");

        assertEquals(LogLevel.INFO, formatter.only().level());
        assertEquals("Hello, World!", formatter.only().message());
    }

    @Test
    public void warnIsFormattedAtWarn() {
        var formatter = new RecordingFormatter();

        logger(formatter).warn("Careful");

        assertEquals(LogLevel.WARN, formatter.only().level());
        assertEquals("Careful", formatter.only().message());
    }

    @Test
    public void errorIsFormattedAtError() {
        var formatter = new RecordingFormatter();

        logger(formatter).error("Boom");

        assertEquals(LogLevel.ERROR, formatter.only().level());
        assertEquals("Boom", formatter.only().message());
    }

    @Test
    public void fatalIsFormattedAtFatal() {
        var formatter = new RecordingFormatter();

        logger(formatter).fatal("Unrecoverable");

        assertEquals(LogLevel.FATAL, formatter.only().level());
        assertEquals("Unrecoverable", formatter.only().message());
    }

    @Test
    public void theLevelDecidesTheColourTheFormatterCanReachFor() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info("green");
        log.warn("yellow");
        log.error("red");

        assertEquals(GREEN, LogLevel.color(formatter.calls.get(0).level()));
        assertEquals(YELLOW, LogLevel.color(formatter.calls.get(1).level()));
        assertEquals(RED, LogLevel.color(formatter.calls.get(2).level()));
    }

    @Test
    public void theLoggerPassesTheCallingThreadsNameAsItsOnlyExtraArgument() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("plain");

        assertEquals(List.of(Thread.currentThread().getName()), formatter.only().args());
    }

    // ---------------------------------------------------------------------
    // The formatter's return value is what gets written.
    // ---------------------------------------------------------------------

    @Test
    public void theFormattedStringIsWhatReachesTheDestination() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("on the wire");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // Levels. The logger carries no threshold of its own: every level is
    // handed to the formatter and written, and severity is left for a
    // caller to compare.
    // ---------------------------------------------------------------------

    @Test
    public void debugIsFormattedAtDebugAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).debug("chatter");

        assertEquals(LogLevel.DEBUG, formatter.only().level());
        assertEquals("chatter", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void traceIsFormattedAtTraceAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).trace("Tracing");

        assertEquals(LogLevel.TRACE, formatter.only().level());
        assertEquals("Tracing", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void everyLevelIsWritten() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.trace("kept");
        log.debug("kept");
        log.info("kept");
        log.warn("kept");
        log.error("kept");
        log.fatal("kept");

        assertEquals(
                List.of(LogLevel.TRACE, LogLevel.DEBUG, LogLevel.INFO,
                        LogLevel.WARN, LogLevel.ERROR, LogLevel.FATAL),
                formatter.calls.stream().map(Call::level).toList());
        assertEquals(6, stdoutText().lines().count());
    }

    @Test
    public void successiveMessagesAccumulateInOrder() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info("first");
        log.error("second");

        assertEquals(2, formatter.calls.size());
        assertEquals("first", formatter.calls.get(0).message());
        assertEquals("second", formatter.calls.get(1).message());
        assertEquals(
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(1).rendered() + NL,
                stdoutText());
    }

    // ---------------------------------------------------------------------
    // Destinations.
    // ---------------------------------------------------------------------

    @Test
    public void logsGoToStdoutWhenNoDestinationIsConfigured() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("to stdout");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
        assertEquals("", stderrText());
    }

    @Test
    public void theStdoutDestinationIsResolvedWhenOptionsAreApplied() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        var replacement = new ByteArrayOutputStream();
        System.setOut(new PrintStream(replacement, true, StandardCharsets.UTF_8));
        log.setOptions(to(LogDestination.STDOUT)).info("to the new stdout");

        assertEquals("the stream captured at construction should be left alone",
                "", stdoutText());
        assertEquals(formatter.only().rendered() + NL,
                replacement.toString(StandardCharsets.UTF_8));
    }

    @Test
    public void theStderrDestinationDivertsAwayFromStdout() {
        var formatter = new RecordingFormatter();

        logger(formatter).setOptions(to(LogDestination.STDERR)).info("to stderr");

        assertEquals(formatter.only().rendered() + NL, stderrText());
        assertEquals("stdout should be untouched once stderr is selected", "", stdoutText());
    }

    @Test
    public void aFileDestinationDivertsAwayFromStdout() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath()))).info("to a file");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("stdout should be untouched once a file is selected", "", stdoutText());
    }

    @Test
    public void reopeningAFileDestinationAppendsRatherThanTruncates() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var destination = to(LogDestination.file(sink.getAbsolutePath()));

        log.setOptions(destination).info("first");
        log.setOptions(destination).info("second");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void switchingAwayFromAFileStopsWritingToIt() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath()))).info("to the file");
        log.setOptions(to(LogDestination.STDOUT)).info("to stdout");

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void optionsWithoutADestinationLeaveThePrinterAlone() {
        var formatter = new RecordingFormatter();

        logger(formatter)
                .setOptions(LogOptions.initiateOptions())
                .info("still on stdout");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void aFileDestinationSurvivesAnEmptyOptionsUpdate() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath())));
        log.setOptions(LogOptions.initiateOptions()).info("still on the file");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("", stdoutText());
    }

    @Test
    public void loggersDoNotShareADestination() throws Exception {
        File sink = tempFolder.newFile();
        var toFile = new RecordingFormatter();
        var toStdout = new RecordingFormatter();

        var fileLog = logger(toFile)
                .setOptions(to(LogDestination.file(sink.getAbsolutePath())));
        var stdoutLog = logger(toStdout);

        fileLog.info("to the file");
        stdoutLog.info("to stdout");
        fileLog.setOptions(to(LogDestination.STDOUT));

        assertEquals(toFile.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(toStdout.only().rendered() + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // setOptions contract.
    // ---------------------------------------------------------------------

    @Test
    public void setOptionsReturnsTheSameLoggerSoCallsCanChain() {
        var log = logger(new RecordingFormatter());

        assertSame(log, log.setOptions(LogOptions.initiateOptions()));
        assertSame(log, log.setOptions(to(LogDestination.STDERR)));
    }

    @Test
    public void anUnusableFileDestinationIsReportedAndThePrinterIsLeftAlone() throws Exception {
        File directory = tempFolder.newFolder();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(directory.getAbsolutePath())));

        String notice = stdoutText();
        assertTrue("expected a failure notice, got: " + notice,
                notice.startsWith("Failed to set log destination:"));

        log.info("still on stdout");
        assertTrue("logging should carry on where it was",
                stdoutText().endsWith(formatter.only().rendered() + NL));
    }

    // ---------------------------------------------------------------------
    // A formatter that throws must not take the logger down with it.
    // ---------------------------------------------------------------------

    @Test
    public void aFailingFormatterIsReportedThroughTheErrorPath() {
        var formatter = new FailsOnceFormatter();

        logger(formatter).info("never formatted");

        assertEquals(1, formatter.calls.size());
        Call recovery = formatter.calls.get(0);
        assertEquals(LogLevel.ERROR, recovery.level());
        assertEquals("formatter exploded", recovery.message());
        assertEquals(recovery.rendered() + NL, stdoutText());
    }

    @Test
    public void aFormatterThatAlwaysFailsFallsBackToAPlainNotice() {
        logger(new AlwaysFailsFormatter()).info("never formatted");

        assertEquals(
                RED + "Failed to format log message: formatter exploded" + RESET + NL,
                stdoutText());
    }

    @Test
    public void aBrokenFormatterNeverStopsTheCaller() {
        var log = logger(new AlwaysFailsFormatter());

        log.info("first");
        log.error("second");

        assertEquals("the caller should keep running either way", 2, stdoutText().lines().count());
    }

    // ---------------------------------------------------------------------
    // Options and destinations as values.
    // ---------------------------------------------------------------------

    @Test
    public void freshOptionsCarryNoDestination() {
        assertNull(LogOptions.initiateOptions().getDestination());
    }

    @Test
    public void setDestinationIsFluentAndRemembersWhatItWasGiven() {
        var options = LogOptions.initiateOptions();

        assertSame(options, options.setDestination(LogDestination.STDERR));
        assertEquals(LogDestination.STDERR, options.getDestination());
    }

    @Test
    public void aFileDestinationCarriesItsPathAndComparesByValue() {
        var one = LogDestination.file("/var/log/a.log");
        var same = LogDestination.file("/var/log/a.log");
        var other = LogDestination.file("/var/log/b.log");

        assertEquals("/var/log/a.log", ((LogDestination.LogFile) one).path());
        assertEquals(one, same);
        assertNotEquals(one, other);
    }

    @Test
    public void theSharedStreamDestinationsAreDistinct() {
        assertTrue(LogDestination.STDOUT instanceof LogDestination.Stdout);
        assertTrue(LogDestination.STDERR instanceof LogDestination.Stderr);
        assertNotEquals(LogDestination.STDOUT, LogDestination.STDERR);
    }

    // ---------------------------------------------------------------------
    // The shipped Formatter.
    // ---------------------------------------------------------------------

    @Test
    public void theShippedFormatterFillsInTheColourThenTheMessage() {
        assertEquals(YELLOW + "[Careful]",
                new Formatter("%s[%s]").getFormattedString(LogLevel.WARN, "Careful"));
    }

    @Test
    public void theShippedFormatterHonoursTheFormatItWasBuiltWith() {
        assertEquals("Careful" + YELLOW,
                new Formatter("%2$s%1$s").getFormattedString(LogLevel.WARN, "Careful"));
    }

    @Test
    public void theDefaultFormatColoursTheMessageAndClosesTheColour() {
        assertEquals(GREEN + "Hello, World!" + RESET,
                new Formatter(Formatable.DEFAULT_FORMAT)
                        .getFormattedString(LogLevel.INFO, "Hello, World!"));
    }

    @Test
    public void theDefaultFormatCarriesAMessageAllTheWayToTheDestination() {
        logger(new Formatter(Formatable.DEFAULT_FORMAT)).warn("Careful");

        assertEquals(YELLOW + "Careful" + RESET + NL, stdoutText());
    }

    @Test
    public void extraArgumentsAreSpreadIntoTheFormatRatherThanPassedAsAnArray() {
        assertEquals(GREEN + "disk full: 91% of 500GB",
                new Formatter("%s%s: %s%% of %sGB")
                        .getFormattedString(LogLevel.INFO, "disk full", 91, 500));
    }

    @Test
    public void surplusArgumentsAreIgnoredByTheFormat() {
        assertEquals(GREEN + "terse",
                new Formatter("%s%s").getFormattedString(LogLevel.INFO, "terse", "unused"));
    }

    @Test
    public void theShippedFormatterWritesItsLineToTheDestination() {
        logger(new Formatter("%s%s" + RESET)).info("Hello, World!");

        assertEquals(GREEN + "Hello, World!" + RESET + NL, stdoutText());
    }

    @Test
    public void theShippedFormatterEmitsOneLinePerCall() {
        var log = logger(new Formatter("%s%s" + RESET));

        log.info("first");
        log.warn("second");
        log.debug("third");

        assertEquals(3, stdoutText().lines().count());
    }

    @Test
    public void theTimestampPatternIsTheOneTheLibraryPublishes() {
        assertEquals("2026-08-22 09:41",
                java.time.LocalDateTime.of(2026, 8, 22, 9, 41).format(Formatter.TIMESTAMP_FORMAT));
    }

    // ---------------------------------------------------------------------
    // Colours are a property of the level itself.
    // ---------------------------------------------------------------------

    @Test
    public void everyLevelMapsToAColour() {
        assertEquals(BLUE, LogLevel.color(LogLevel.TRACE));
        assertEquals(BLUE, LogLevel.color(LogLevel.DEBUG));
        assertEquals(GREEN, LogLevel.color(LogLevel.INFO));
        assertEquals(YELLOW, LogLevel.color(LogLevel.WARN));
        assertEquals(RED, LogLevel.color(LogLevel.ERROR));
        assertEquals(RED, LogLevel.color(LogLevel.FATAL));
        assertEquals(RESET, LogLevel.color(LogLevel.RESET));
    }

    @Test
    public void severityIncreasesWithTheLevel() {
        assertTrue(LogLevel.TRACE.severity() < LogLevel.DEBUG.severity());
        assertTrue(LogLevel.DEBUG.severity() < LogLevel.INFO.severity());
        assertTrue(LogLevel.INFO.severity() < LogLevel.WARN.severity());
        assertTrue(LogLevel.WARN.severity() < LogLevel.ERROR.severity());
        assertTrue(LogLevel.ERROR.severity() < LogLevel.FATAL.severity());
    }
}
