/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;

import org.junit.After;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class LoggingTest {
    private static final String ESC = String.valueOf((char) 27);
    private static final String RESET = ESC + "[0m";
    private static final String GREEN = ESC + "[32m";
    private static final String YELLOW = ESC + "[33m";
    private static final String RED = ESC + "[31m";
    private static final String BLUE = ESC + "[34m";

    private static final String NL = System.lineSeparator();

    /** Fixed timestamp for events built directly, to test PatternFormatter on its own. */
    private static final long AT = 1_700_000_000_000L;

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    // ---------------------------------------------------------------------
    // Test doubles.
    //
    // The logger builds a LogEvent from the call and hands it to the
    // formatter, then prints whatever string comes back. Unpacking the event
    // here is what makes the level and the message assertable, and the
    // returned string is what should turn up at the destination.
    // ---------------------------------------------------------------------

    private record Call(LogLevel level, String message, long timestamp,
            String threadName, Throwable thrown) {

        static Call of(LogEvent event) {
            return new Call(event.getLevel(), event.getMessage(), event.getTimestamp(),
                    event.getThreadName(), event.getThrown());
        }

        String rendered() {
            return LogLevel.color(level) + "[" + level + "] " + message + RESET;
        }
    }

    private static final class RecordingFormatter implements LogFormatter {
        private final List<Call> calls = new ArrayList<>();

        @Override
        public String format(LogEvent event) {
            var call = Call.of(event);
            calls.add(call);
            return call.rendered();
        }

        Call only() {
            assertEquals("expected exactly one formatted line", 1, calls.size());
            return calls.get(0);
        }
    }

    /** Throws on its first call only, so the logger's recovery path can format. */
    private static final class FailsOnceFormatter implements LogFormatter {
        private final List<Call> calls = new ArrayList<>();
        private boolean armed = true;

        @Override
        public String format(LogEvent event) {
            if (armed) {
                armed = false;
                throw new IllegalStateException("formatter exploded");
            }
            var call = Call.of(event);
            calls.add(call);
            return call.rendered();
        }
    }

    private static final class AlwaysFailsFormatter implements LogFormatter {
        @Override
        public String format(LogEvent event) {
            throw new IllegalStateException("formatter exploded");
        }
    }

    // ---------------------------------------------------------------------
    // Standard streams are redirected for every test, so a logger built with
    // the default destination writes somewhere we can read back.
    // ---------------------------------------------------------------------

    private final PrintStream realStdout = System.out;
    private final PrintStream realStderr = System.err;

    private ByteArrayOutputStream stdout;
    private ByteArrayOutputStream stderr;

    @Before
    public void redirectStandardStreams() {
        stdout = new ByteArrayOutputStream();
        stderr = new ByteArrayOutputStream();
        System.setOut(new PrintStream(stdout, true, StandardCharsets.UTF_8));
        System.setErr(new PrintStream(stderr, true, StandardCharsets.UTF_8));
    }

    @After
    public void restoreStandardStreams() {
        System.setOut(realStdout);
        System.setErr(realStderr);
    }

    private String stdoutText() {
        return stdout.toString(StandardCharsets.UTF_8);
    }

    private String stderrText() {
        return stderr.toString(StandardCharsets.UTF_8);
    }

    private static LogOptions to(LogDestination destination) {
        return LogOptions.initiateOptions().setDestination(destination);
    }

    /**
     * Logging only publishes the two-argument factory, so tests go through this.
     */
    private static Loggable logger(LogFormatter formatter) {
        return Logging.getLogger(formatter, LogOptions.initiateOptions());
    }

    private static LogOptions with(LogFormatter formatter) {
        return LogOptions.initiateOptions().setFormatter(formatter);
    }

    // ---------------------------------------------------------------------
    // Each level method logs at its own level.
    //
    // The method that was called is now the only thing that decides the
    // level: the logger builds the event, so a caller cannot disagree with it.
    // ---------------------------------------------------------------------

    @Test
    public void infoLogsAtInfoAndCarriesTheMessage() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("Hello, World!");

        assertEquals(LogLevel.INFO, formatter.only().level());
        assertEquals("Hello, World!", formatter.only().message());
    }

    @Test
    public void warnLogsAtWarn() {
        var formatter = new RecordingFormatter();

        logger(formatter).warn("Careful");

        assertEquals(LogLevel.WARN, formatter.only().level());
        assertEquals("Careful", formatter.only().message());
    }

    @Test
    public void errorLogsAtError() {
        var formatter = new RecordingFormatter();

        logger(formatter).error("Boom");

        assertEquals(LogLevel.ERROR, formatter.only().level());
        assertEquals("Boom", formatter.only().message());
    }

    @Test
    public void fatalLogsAtFatal() {
        var formatter = new RecordingFormatter();

        logger(formatter).fatal("Unrecoverable");

        assertEquals(LogLevel.FATAL, formatter.only().level());
        assertEquals("Unrecoverable", formatter.only().message());
    }

    @Test
    public void debugLogsAtDebugAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).debug("chatter");

        assertEquals(LogLevel.DEBUG, formatter.only().level());
        assertEquals("chatter", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void traceLogsAtTraceAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).trace("Tracing");

        assertEquals(LogLevel.TRACE, formatter.only().level());
        assertEquals("Tracing", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void everySixMethodsMapToTheirOwnLevelInOrder() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.trace("kept");
        log.debug("kept");
        log.info("kept");
        log.warn("kept");
        log.error("kept");
        log.fatal("kept");

        assertEquals(
                List.of(LogLevel.TRACE, LogLevel.DEBUG, LogLevel.INFO,
                        LogLevel.WARN, LogLevel.ERROR, LogLevel.FATAL),
                formatter.calls.stream().map(Call::level).toList());
        assertEquals(6, stdoutText().lines().count());
    }

    @Test
    public void theLevelDecidesTheColourTheFormatterCanReachFor() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info("green");
        log.warn("yellow");
        log.error("red");

        assertEquals(GREEN, LogLevel.color(formatter.calls.get(0).level()));
        assertEquals(YELLOW, LogLevel.color(formatter.calls.get(1).level()));
        assertEquals(RED, LogLevel.color(formatter.calls.get(2).level()));
    }

    @Test
    public void theLoggerStampsTheEventItBuilds() {
        var formatter = new RecordingFormatter();

        long before = System.currentTimeMillis();
        logger(formatter).info("stamped");
        long after = System.currentTimeMillis();

        assertTrue("the timestamp should be taken at the call",
                formatter.only().timestamp() >= before
                        && formatter.only().timestamp() <= after);
        assertEquals(Thread.currentThread().getName(), formatter.only().threadName());
    }

    // ---------------------------------------------------------------------
    // The formatter's return value is what gets written.
    // ---------------------------------------------------------------------

    @Test
    public void theFormattedStringIsWhatReachesTheDestination() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("on the wire");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void successiveMessagesAccumulateInOrder() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info("first");
        log.error("second");

        assertEquals(2, formatter.calls.size());
        assertEquals("first", formatter.calls.get(0).message());
        assertEquals("second", formatter.calls.get(1).message());
        assertEquals(
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(1).rendered() + NL,
                stdoutText());
    }

    // ---------------------------------------------------------------------
    // Destinations.
    // ---------------------------------------------------------------------

    @Test
    public void logsGoToStdoutWhenNoDestinationIsConfigured() {
        var formatter = new RecordingFormatter();

        logger(formatter).info("to stdout");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
        assertEquals("", stderrText());
    }

    @Test
    public void theStdoutDestinationIsResolvedWhenOptionsAreApplied() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        var replacement = new ByteArrayOutputStream();
        System.setOut(new PrintStream(replacement, true, StandardCharsets.UTF_8));
        log.setOptions(to(LogDestination.STDOUT)).info("to the new stdout");

        assertEquals("the stream captured at construction should be left alone",
                "", stdoutText());
        assertEquals(formatter.only().rendered() + NL,
                replacement.toString(StandardCharsets.UTF_8));
    }

    @Test
    public void theStderrDestinationDivertsAwayFromStdout() {
        var formatter = new RecordingFormatter();

        logger(formatter).setOptions(to(LogDestination.STDERR)).info("to stderr");

        assertEquals(formatter.only().rendered() + NL, stderrText());
        assertEquals("stdout should be untouched once stderr is selected", "", stdoutText());
    }

    @Test
    public void aFileDestinationDivertsAwayFromStdout() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath()))).info("to a file");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("stdout should be untouched once a file is selected", "", stdoutText());
    }

    @Test
    public void reopeningAFileDestinationAppendsRatherThanTruncates() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var destination = to(LogDestination.file(sink.getAbsolutePath()));

        log.setOptions(destination).info("first");
        log.setOptions(destination).info("second");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void switchingAwayFromAFileStopsWritingToIt() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath()))).info("to the file");
        log.setOptions(to(LogDestination.STDOUT)).info("to stdout");

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void optionsWithoutADestinationLeaveThePrinterAlone() {
        var formatter = new RecordingFormatter();

        logger(formatter)
                .setOptions(LogOptions.initiateOptions())
                .info("still on stdout");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void aFileDestinationSurvivesAnEmptyOptionsUpdate() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath())));
        log.setOptions(LogOptions.initiateOptions()).info("still on the file");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("", stdoutText());
    }

    @Test
    public void loggersDoNotShareADestination() throws Exception {
        File sink = tempFolder.newFile();
        var toFile = new RecordingFormatter();
        var toStdout = new RecordingFormatter();

        var fileLog = logger(toFile)
                .setOptions(to(LogDestination.file(sink.getAbsolutePath())));
        var stdoutLog = logger(toStdout);

        fileLog.info("to the file");
        stdoutLog.info("to stdout");
        fileLog.setOptions(to(LogDestination.STDOUT));

        assertEquals(toFile.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(toStdout.only().rendered() + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // setOptions contract.
    // ---------------------------------------------------------------------

    @Test
    public void setOptionsReturnsTheSameLoggerSoCallsCanChain() {
        var log = logger(new RecordingFormatter());

        assertSame(log, log.setOptions(LogOptions.initiateOptions()));
        assertSame(log, log.setOptions(to(LogDestination.STDERR)));
    }

    @Test
    public void setCurrentLevelReturnsTheSameLoggerSoCallsCanChain() {
        var log = logger(new RecordingFormatter());

        assertSame(log, log.setCurrentLevel(LogLevel.WARN));
    }

    @Test
    public void anUnusableFileDestinationIsReportedAndThePrinterIsLeftAlone() throws Exception {
        File directory = tempFolder.newFolder();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(directory.getAbsolutePath())));

        String notice = stdoutText();
        assertTrue("expected a failure notice, got: " + notice,
                notice.startsWith("Failed to set log destination:"));

        log.info("still on stdout");
        assertTrue("logging should carry on where it was",
                stdoutText().endsWith(formatter.only().rendered() + NL));
    }

    // ---------------------------------------------------------------------
    // Runtime reconfiguration.
    //
    // setOptions can be called at any point in a logger's life. What follows
    // pins down what a reconfiguration does to the messages around it: the
    // ones already written, the ones still to come, the stream being left
    // behind, and any other logger that happens to share it.
    // ---------------------------------------------------------------------

    @Test
    public void eachMessageGoesWhereverTheLoggerPointedWhenItWasCalled() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info("before the move");
        log.setOptions(to(LogDestination.file(sink.getAbsolutePath()))).info("while on the file");
        log.setOptions(to(LogDestination.STDERR)).info("while on stderr");
        log.setOptions(to(LogDestination.STDOUT)).info("back on stdout");

        assertEquals("reconfiguring is not retroactive",
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(3).rendered() + NL,
                stdoutText());
        assertEquals(formatter.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(2).rendered() + NL, stderrText());
    }

    @Test
    public void movingFromOneFileToAnotherLeavesTheFirstCompleteAndUntouched() throws Exception {
        File first = tempFolder.newFile();
        File second = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(first.getAbsolutePath()))).info("into the first");
        log.setOptions(to(LogDestination.file(second.getAbsolutePath()))).info("into the second");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(first.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL,
                Files.readString(second.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void comingBackToAFileAppendsToWhatIsAlreadyThere() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var toSink = to(LogDestination.file(sink.getAbsolutePath()));

        log.setOptions(toSink).info("first visit");
        log.setOptions(to(LogDestination.STDOUT)).info("away for a moment");
        log.setOptions(toSink).info("second visit");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals("returning to a file must not truncate it",
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(2).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void aReconfigurationThatFailsReportsToTheDestinationStillInUse() throws Exception {
        File sink = tempFolder.newFile();
        File directory = tempFolder.newFolder();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.file(sink.getAbsolutePath())));
        log.setOptions(to(LogDestination.file(directory.getAbsolutePath())));
        log.info("still on the file");
        log.setOptions(to(LogDestination.STDOUT));

        String written = Files.readString(sink.toPath(), StandardCharsets.UTF_8);
        assertTrue("the notice belongs wherever the logger is currently writing, got: " + written,
                written.startsWith("Failed to set log destination:"));
        assertTrue("the working destination should survive a failed move",
                written.endsWith(formatter.only().rendered() + NL));
        assertEquals("a failed move must not fall back to stdout", "", stdoutText());
    }

    @Test
    public void reselectingTheSameDestinationChangesNothing() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.STDOUT));
        log.setOptions(to(LogDestination.STDOUT));
        log.setOptions(to(LogDestination.STDOUT)).info("once only");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void movingBetweenTheSharedStreamsNeverClosesThem() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setOptions(to(LogDestination.STDERR));
        log.setOptions(to(LogDestination.STDOUT));
        log.setOptions(to(LogDestination.STDERR)).info("to stderr");
        log.setOptions(to(LogDestination.STDOUT)).info("to stdout");

        assertFalse("System.out must not be closed on the way past", System.out.checkError());
        assertFalse("System.err must not be closed on the way past", System.err.checkError());
        assertEquals(formatter.calls.get(0).rendered() + NL, stderrText());
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void theOptionsAreReadOnceAndNotHeldOnTo() {
        var formatter = new RecordingFormatter();
        var options = to(LogDestination.STDERR);
        var log = logger(formatter).setOptions(options);

        options.setDestination(LogDestination.STDOUT);
        log.info("still on stderr");

        assertEquals("a later edit to the options object must not move the logger",
                formatter.only().rendered() + NL, stderrText());
        assertEquals("", stdoutText());
    }

    @Test
    public void aLoggerBuiltOnAFileCanBeMovedOffItLater() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();

        var log = Logging.getLogger(formatter, to(LogDestination.file(sink.getAbsolutePath())));
        log.info("into the file");
        log.setOptions(to(LogDestination.STDOUT)).info("out to stdout");

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void oneLoggerMovingOffAFileLeavesAnotherStillWritingToIt() throws Exception {
        File sink = tempFolder.newFile();
        var leaving = new RecordingFormatter();
        var staying = new RecordingFormatter();
        var toSink = to(LogDestination.file(sink.getAbsolutePath()));

        var leaves = logger(leaving).setOptions(toSink);
        var stays = logger(staying).setOptions(toSink);

        leaves.info("from the one that leaves");
        stays.info("from the one that stays");
        leaves.setOptions(to(LogDestination.STDOUT));
        stays.info("after the other one left");
        stays.setOptions(to(LogDestination.STDOUT));

        assertEquals(
                leaving.only().rendered() + NL
                        + staying.calls.get(0).rendered() + NL
                        + staying.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    // ---------------------------------------------------------------------
    // Runtime configuration of the formatter.
    // ---------------------------------------------------------------------

    @Test
    public void aFormatterSetAtRuntimeReplacesTheOneTheLoggerWasBuiltWith() {
        var original = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var log = logger(original);

        log.info("through the original");
        log.setOptions(with(replacement)).info("through the replacement");

        assertEquals("through the original", original.only().message());
        assertEquals("through the replacement", replacement.only().message());
        assertEquals(original.only().rendered() + NL + replacement.only().rendered() + NL,
                stdoutText());
    }

    @Test
    public void theFormatterAndTheDestinationCanMoveInTheSameCall() throws Exception {
        File sink = tempFolder.newFile();
        var original = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var log = logger(original);

        log.info("original, on stdout");
        log.setOptions(with(replacement)
                .setDestination(LogDestination.file(sink.getAbsolutePath())))
                .info("replacement, on the file");
        log.setOptions(to(LogDestination.STDOUT));

        assertEquals(original.only().rendered() + NL, stdoutText());
        assertEquals(replacement.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void optionsWithoutAFormatterLeaveTheOneInPlace() {
        var formatter = new RecordingFormatter();

        logger(formatter).setOptions(to(LogDestination.STDERR)).info("same formatter as before");

        assertEquals(formatter.only().rendered() + NL, stderrText());
    }

    @Test
    public void swappingFormattersChangesTheShapeOfTheLinesThatFollow() {
        var log = logger(new PatternFormatter("[%s]"));

        log.info("first");
        log.setOptions(with(new PatternFormatter("<%s>"))).info("second");

        assertEquals("the swap must not reach back over what was already written",
                "[first]" + NL + "<second>" + NL, stdoutText());
    }

    @Test
    public void aFormatterSetAtRuntimeIsGivenTheWholeEvent() {
        var replacement = new RecordingFormatter();

        logger(new RecordingFormatter()).setOptions(with(replacement)).warn("Careful");

        assertEquals(LogLevel.WARN, replacement.only().level());
        assertEquals("Careful", replacement.only().message());
        assertEquals(Thread.currentThread().getName(), replacement.only().threadName());
    }

    @Test
    public void swappingInAWorkingFormatterRecoversALoggerThatCouldNotFormat() {
        var replacement = new RecordingFormatter();
        var log = logger(new AlwaysFailsFormatter());

        log.info("never formatted");
        log.setOptions(with(replacement)).info("formatted at last");

        assertEquals(
                RED + "Failed to format log message: "
                        + "java.lang.IllegalStateException: formatter exploded" + RESET + NL
                        + replacement.only().rendered() + NL,
                stdoutText());
    }

    @Test
    public void swappingInABrokenFormatterIsStillNotFatal() {
        var log = logger(new RecordingFormatter());

        log.setOptions(with(new AlwaysFailsFormatter()));
        log.info("first");
        log.error("second");

        assertEquals("the caller should keep running either way", 2, stdoutText().lines().count());
    }

    @Test
    public void theFormatterIsReadOnceAndNotHeldOnTo() {
        var replacement = new RecordingFormatter();
        var neverApplied = new RecordingFormatter();
        var options = with(replacement);
        var log = logger(new RecordingFormatter()).setOptions(options);

        options.setFormatter(neverApplied);
        log.info("through the replacement");

        assertEquals("a later edit to the options object must not reach the logger",
                "through the replacement", replacement.only().message());
        assertEquals(List.of(), neverApplied.calls);
    }

    @Test
    public void swappingOneLoggersFormatterLeavesAnotherLoggerOnTheOldOne() {
        var shared = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var swapped = logger(shared);
        var untouched = logger(shared);

        swapped.setOptions(with(replacement)).info("through the replacement");
        untouched.info("still through the shared one");

        assertEquals("through the replacement", replacement.only().message());
        assertEquals("still through the shared one", shared.only().message());
    }

    // ---------------------------------------------------------------------
    // A formatter that throws must not take the logger down with it.
    // ---------------------------------------------------------------------

    @Test
    public void aFailingFormatterIsReportedThroughTheErrorPath() {
        var formatter = new FailsOnceFormatter();

        logger(formatter).info("never formatted");

        assertEquals(1, formatter.calls.size());
        Call recovery = formatter.calls.get(0);
        assertEquals("the recovery line is reported at ERROR whatever failed",
                LogLevel.ERROR, recovery.level());
        assertEquals("Failed to format log message", recovery.message());
        assertEquals("the failure travels on the event rather than inside its message",
                "formatter exploded", recovery.thrown().getMessage());
        assertTrue("expected the rendered line first, got: " + stdoutText(),
                stdoutText().startsWith(recovery.rendered() + NL));
    }

    @Test
    public void theRecoveryLineCarriesTheFailureOnlyOnTheEvent() {
        var formatter = new FailsOnceFormatter();

        logger(formatter).info("never formatted");

        // reportFormattingFailure prints just the formatted line, so what the
        // reader sees depends entirely on whether their LogFormatter reaches for
        // event.getThrown(). The recording one here does not.
        assertEquals(formatter.calls.get(0).rendered() + NL, stdoutText());
        assertEquals("formatter exploded", formatter.calls.get(0).thrown().getMessage());
    }

    @Test
    public void aFormatterThatAlwaysFailsFallsBackToAPlainNotice() {
        logger(new AlwaysFailsFormatter()).info("never formatted");

        // The last-ditch branch uses toString(), so the exception type survives
        // even when getMessage() would have been null.
        assertEquals(
                RED + "Failed to format log message: "
                        + "java.lang.IllegalStateException: formatter exploded" + RESET + NL,
                stdoutText());
    }

    @Test
    public void aBrokenFormatterNeverStopsTheCaller() {
        var log = logger(new AlwaysFailsFormatter());

        log.info("first");
        log.error("second");

        assertEquals("the caller should keep running either way", 2, stdoutText().lines().count());
    }

    // ---------------------------------------------------------------------
    // Exceptions.
    //
    // A throwable is the application's failure, not the logger's: the caller
    // hands over the object rather than a string, so the logger can render the
    // frames and the cause chain, and can decline to render anything at all
    // when the line is suppressed.
    // ---------------------------------------------------------------------

    @Test
    public void theExceptionReachesTheFormatterOnTheEvent() {
        var formatter = new RecordingFormatter();
        var boom = new IllegalStateException("payment declined");

        logger(formatter).error("payment failed", boom);

        assertSame(boom, formatter.only().thrown());
        assertEquals(LogLevel.ERROR, formatter.only().level());
        assertEquals("payment failed", formatter.only().message());
    }

    @Test
    public void theExceptionIsPrintedBeneathTheLineItBelongsTo() {
        var formatter = new RecordingFormatter();

        logger(formatter).error("payment failed", new IllegalStateException("payment declined"));

        assertEquals(formatter.only().rendered() + NL
                + "java.lang.IllegalStateException: payment declined" + NL,
                stdoutText());
    }

    @Test
    public void anExceptionIsRenderedByToStringSoNoFramesAppear() {
        var formatter = new RecordingFormatter();

        logger(formatter).error("payment failed", new IllegalStateException("payment declined"));

        // Characterises the rendering in use: Throwable.toString() gives the
        // type and the message. Switching to printStackTrace would add the
        // frames, and this test is where that change would announce itself.
        assertFalse("toString carries no frames, got: " + stdoutText(),
                stdoutText().contains("at org.example.LoggingTest"));
    }

    @Test
    public void aWrappedExceptionShowsOnlyItsOutermostLayer() {
        var cause = new ArrayIndexOutOfBoundsException("Index 3 out of bounds for length 0");
        var wrapper = new IllegalStateException("could not load order 4711", cause);

        logger(new PatternFormatter("%s")).error("load failed", wrapper);

        String written = stdoutText();
        assertTrue("the wrapper is named, got: " + written,
                written.contains("java.lang.IllegalStateException: could not load order 4711"));
        assertFalse("toString stops at the outermost exception, got: " + written,
                written.contains("ArrayIndexOutOfBoundsException"));
    }

    @Test
    public void everyLevelMethodAcceptsAThrowable() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var boom = new IllegalStateException("boom");

        log.trace("t", boom);
        log.debug("d", boom);
        log.info("i", boom);
        log.warn("w", boom);
        log.error("e", boom);
        log.fatal("f", boom);

        assertEquals(
                List.of(LogLevel.TRACE, LogLevel.DEBUG, LogLevel.INFO,
                        LogLevel.WARN, LogLevel.ERROR, LogLevel.FATAL),
                formatter.calls.stream().map(Call::level).toList());
        assertEquals(Collections.nCopies(6, boom),
                formatter.calls.stream().map(Call::thrown).toList());
    }

    @Test
    public void aNullThrowableLogsExactlyLikeTheOneArgumentCall() {
        var passingNull = new RecordingFormatter();
        logger(passingNull).info("same either way", null);
        String withNull = stdoutText();

        stdout.reset();
        var omitting = new RecordingFormatter();
        logger(omitting).info("same either way");

        assertNull(passingNull.only().thrown());
        assertNull(omitting.only().thrown());
        assertEquals(withNull, stdoutText());
    }

    @Test
    public void aSuppressedCallNeverRendersItsException() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setCurrentLevel(LogLevel.ERROR);
        log.debug("expensive to render", new IllegalStateException("never rendered"));

        assertEquals("rendering a stack trace is exactly the work a threshold should save",
                List.of(), formatter.calls);
        assertEquals("", stdoutText());
    }

    @Test
    public void theGeneralLogMethodIsUsableDirectly() {
        var formatter = new RecordingFormatter();

        logger(formatter).log(LogLevel.WARN, "through the general method", null);

        assertEquals(LogLevel.WARN, formatter.only().level());
        assertEquals("through the general method", formatter.only().message());
    }

    // ---------------------------------------------------------------------
    // Options and destinations as values.
    // ---------------------------------------------------------------------

    @Test
    public void freshOptionsCarryNoDestination() {
        assertNull(LogOptions.initiateOptions().getDestination());
    }

    @Test
    public void setDestinationIsFluentAndRemembersWhatItWasGiven() {
        var options = LogOptions.initiateOptions();

        assertSame(options, options.setDestination(LogDestination.STDERR));
        assertEquals(LogDestination.STDERR, options.getDestination());
    }

    @Test
    public void aFileDestinationCarriesItsPathAndComparesByValue() {
        var one = LogDestination.file("/var/log/a.log");
        var same = LogDestination.file("/var/log/a.log");
        var other = LogDestination.file("/var/log/b.log");

        assertEquals("/var/log/a.log", ((LogDestination.LogFile) one).path());
        assertEquals(one, same);
        assertNotEquals(one, other);
    }

    @Test
    public void theSharedStreamDestinationsAreDistinct() {
        assertTrue(LogDestination.STDOUT instanceof LogDestination.Stdout);
        assertTrue(LogDestination.STDERR instanceof LogDestination.Stderr);
        assertNotEquals(LogDestination.STDOUT, LogDestination.STDERR);
    }

    // ---------------------------------------------------------------------
    // The shipped PatternFormatter, exercised directly.
    // ---------------------------------------------------------------------

    @Test
    public void theShippedFormatterFillsItsConversionWithTheMessage() {
        assertEquals("[Careful]",
                new PatternFormatter("[%s]")
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT)));
    }

    @Test
    public void theShippedFormatterHonoursTheFormatItWasBuiltWith() {
        assertEquals("<<Careful>>",
                new PatternFormatter("<<%s>>")
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT)));
    }

    @Test
    public void theShippedFormatterAddsNoColourOfItsOwn() {
        var log = logger(new PatternFormatter("%s"));

        log.warn("careful");
        log.error("boom");

        assertEquals("careful" + NL + "boom" + NL, stdoutText());
    }

    @Test
    public void theColouredWrapperColoursByTheLevelTheEventCarries() {
        var log = logger(LogFormatter.colored(new PatternFormatter("%s")));

        log.warn("careful");
        log.error("boom");

        assertEquals(YELLOW + "careful" + RESET + NL + RED + "boom" + RESET + NL, stdoutText());
    }

    @Test
    public void theColouredWrapperKeepsWhateverLayoutItWraps() {
        assertEquals(YELLOW + "[Careful]" + RESET,
                LogFormatter.colored(new PatternFormatter("[%s]"))
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT)));
    }

    @Test
    public void theDefaultFormatRendersTheMessageAndNothingElse() {
        assertEquals("Hello, World!",
                new PatternFormatter(PatternFormatter.DEFAULT_PATTERN)
                        .format(LogEvent.create("Hello, World!", LogLevel.INFO, AT)));
    }

    @Test
    public void theDefaultFormatCarriesAMessageAllTheWayToTheDestination() {
        logger(new PatternFormatter(PatternFormatter.DEFAULT_PATTERN)).warn("Careful");

        assertEquals("Careful" + NL, stdoutText());
    }

    @Test
    public void aFileDestinationGetsNoEscapeSequencesFromTheDefaultFormat() throws Exception {
        // Colour belongs to the destination, so an uncoloured formatter is what
        // keeps escape sequences out of a file someone will later grep.
        File sink = tempFolder.newFile();
        Logging.getLogger(new PatternFormatter(PatternFormatter.DEFAULT_PATTERN),
                to(LogDestination.file(sink.getAbsolutePath()))).info("user signed in");

        var written = Files.readString(sink.toPath());
        assertFalse("no escape sequences belong in a file, got: " + written,
                written.contains(ESC));
        assertEquals("user signed in" + NL, written);
    }

    @Test
    public void aFormatterBuiltWithoutAPatternIsRejectedAtTheConstructor() {
        assertThrows(NullPointerException.class, () -> new PatternFormatter(null));
    }

    @Test
    public void aFormatReachingPastTheMessageFailsThroughTheLogger() {
        // The formatter is handed the message and nothing else, so a format
        // expecting a second argument has nothing to fill it with and comes out
        // through the recovery path rather than reaching the caller.
        logger(new PatternFormatter("%s %2$s")).info("needs a second argument");

        assertTrue("expected the failure to be reported, got: " + stdoutText(),
                stdoutText().contains("Failed to format log message:"));
    }

    @Test
    public void theShippedFormatterWritesItsLineToTheDestination() {
        logger(new PatternFormatter("%s")).info("Hello, World!");

        assertEquals("Hello, World!" + NL, stdoutText());
    }

    @Test
    public void theShippedFormatterEmitsOneLinePerCall() {
        var log = logger(new PatternFormatter("%s"));

        log.info("first");
        log.warn("second");
        log.debug("third");

        assertEquals(3, stdoutText().lines().count());
    }

    @Test
    public void theShippedFormatterLeavesTheTimestampAndThreadNameToOtherLayouts() {
        // PatternFormatter spends only the message. The event still carries the rest,
        // so a LogFormatter that wants them can reach for them.
        logger(new PatternFormatter("%s")).info("terse");

        assertEquals("terse" + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // Colours are a property of the level itself.
    // ---------------------------------------------------------------------

    @Test
    public void everyLevelMapsToAColour() {
        assertEquals(BLUE, LogLevel.color(LogLevel.TRACE));
        assertEquals(BLUE, LogLevel.color(LogLevel.DEBUG));
        assertEquals(GREEN, LogLevel.color(LogLevel.INFO));
        assertEquals(YELLOW, LogLevel.color(LogLevel.WARN));
        assertEquals(RED, LogLevel.color(LogLevel.ERROR));
        assertEquals(RED, LogLevel.color(LogLevel.FATAL));
        assertEquals(RESET, LogLevel.color(LogLevel.OFF));
    }

    @Test
    public void severityIncreasesWithTheLevel() {
        assertTrue(LogLevel.TRACE.severity() < LogLevel.DEBUG.severity());
        assertTrue(LogLevel.DEBUG.severity() < LogLevel.INFO.severity());
        assertTrue(LogLevel.INFO.severity() < LogLevel.WARN.severity());
        assertTrue(LogLevel.WARN.severity() < LogLevel.ERROR.severity());
        assertTrue(LogLevel.ERROR.severity() < LogLevel.FATAL.severity());
    }

    // ---------------------------------------------------------------------
    // Concurrency.
    //
    // The level methods are no longer synchronized -- only the write is -- so
    // formatting now happens off the lock and several threads can be inside a
    // formatter at once. What must still hold is that a line reaches the
    // destination whole: nothing spliced into the middle of it, nothing lost,
    // nothing written twice.
    // ---------------------------------------------------------------------

    @Test
    public void concurrentLoggingWritesEveryLineWholeAndExactlyOnce() throws Exception {
        File sink = tempFolder.newFile();
        var log = Logging.getLogger(new PatternFormatter("%s"),
                to(LogDestination.file(sink.getAbsolutePath())));

        int threadCount = 4;
        int perThread = 50;
        var start = new CountDownLatch(1);
        var workers = new ArrayList<Thread>();
        var expected = new ArrayList<String>();

        for (int t = 0; t < threadCount; t++) {
            String tag = "worker-" + t;
            for (int i = 0; i < perThread; i++) {
                expected.add(line(tag, i));
            }
            var worker = new Thread(() -> {
                await(start);
                for (int i = 0; i < perThread; i++) {
                    log.info(line(tag, i));
                }
            }, tag);
            workers.add(worker);
            worker.start();
        }

        start.countDown();
        for (Thread worker : workers) {
            worker.join(10_000);
            assertFalse(worker.getName() + " did not finish", worker.isAlive());
        }
        log.setOptions(to(LogDestination.STDOUT));

        List<String> written = Files.readAllLines(sink.toPath(), StandardCharsets.UTF_8);
        assertEquals(threadCount * perThread, written.size());

        Collections.sort(expected);
        Collections.sort(written);
        assertEquals("every line must arrive whole and exactly once", expected, written);
    }

    /** Long enough that a torn write would be obvious in the comparison. */
    private static String line(String tag, int i) {
        return tag + "-" + i + "-" + "x".repeat(40);
    }

    private static void await(CountDownLatch latch) {
        try {
            latch.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(e);
        }
    }

}
