/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.FileOutputStream;
import java.io.PrintStream;
import java.time.LocalDateTime;

public class Logging implements Loggable {

    private Formatable format;

    private final LogLevel currentLogLevel = LogLevel.INFO;
    private PrintStream printer = System.out;
    private boolean ownsPrinter = false;

    public static Loggable getLogger(Formatable formatter) {
        var logger = new Logging();
        logger.format = formatter;
        return logger;
    }

    public Loggable setFormatterWithArgs(Formatable formatter) {
        this.format = formatter;
        return this;
    }

    public Loggable setOptions(LogOptions options) {
        var destination = options.getDestination();
        if (destination == null) {
            return this;
        }
        try {
            PrintStream next = switch (destination) {
                case LogDestination.Stdout ignored ->
                    System.out;
                case LogDestination.Stderr ignored ->
                    System.err;
                case LogDestination.LogFile logFile ->
                    new PrintStream(new FileOutputStream(logFile.path(), true), true);
            };
            if (this.ownsPrinter) {
                this.printer.close();
            }
            this.printer = next;
            this.ownsPrinter = destination instanceof LogDestination.LogFile;
        } catch (Exception e) {
            this.printer.println("Failed to set log destination: " + e.getMessage());
        }
        return this;
    }

    private synchronized void log(String message, LogLevel level) {
        try {
            if (level.severity() < this.currentLogLevel.severity()) {
                return;
            }
            var timestamp = LocalDateTime.now().format(Formatter.TIMESTAMP_FORMAT);
            this.format.getFormattedString(LogLevel.color(level), timestamp, message);
            this.printer.println(this.format);
        } catch (Exception e) {
            var timestamp = LocalDateTime.now().format(Formatter.TIMESTAMP_FORMAT);
            this.format.getFormattedString(LogLevel.color(LogLevel.ERROR), timestamp, e.getMessage());
            this.printer.println(this.format);
        }

    }

    public synchronized void debug(String message) {
        log(message, LogLevel.DEBUG);
    }

    public synchronized void info(String message) {
        log(message, LogLevel.INFO);
    }

    public synchronized void warn(String message) {
        log(message, LogLevel.WARN);
    }

    public synchronized void error(String message) {
        log(message, LogLevel.ERROR);
    }

    public synchronized void trace(String message) {
        log(message, LogLevel.TRACE);
    }

    public synchronized void fatal(String message) {
        log(message, LogLevel.FATAL);
    }
}
