/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.FileOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

public class Logging implements Loggable {

    private static final String LINE_SEPARATOR = System.lineSeparator();
    private static final String THREAD_NAME_KEY = "threadName";

    private LogLevel currentLevel = LogLevel.TRACE;
    private Formatable formatter;
    private Context context;

    private PrintStream printer = System.out;
    private boolean ownsPrinter = false;

    public static Loggable getLogger(Formatable formatter, LogOptions options) {
        var logger = new Logging();
        logger.formatter = formatter;
        logger.setOptions(options);
        logger.context = new Context();
        logger.context.put("threadName", Thread.currentThread().getName());
        return logger;
    }

    @Override
    public synchronized Loggable setCurrentLevel(LogLevel level) {
        this.currentLevel = level;
        return this;
    }

    @Override
    public synchronized Loggable setOptions(LogOptions options) {
        var newFormatter = options.getFormatter();
        if (newFormatter != null) {
            this.formatter = newFormatter;
        }

        var destination = options.getDestination();
        if (destination == null) {
            return this;
        }
        try {
            PrintStream next = switch (destination) {
                case LogDestination.Stdout ignored ->
                    System.out;
                case LogDestination.Stderr ignored ->
                    System.err;
                case LogDestination.LogFile logFile ->
                    new PrintStream(new FileOutputStream(logFile.path(), true), true);
            };
            if (this.ownsPrinter) {
                this.printer.close();
            }
            this.printer = next;
            this.ownsPrinter = destination instanceof LogDestination.LogFile;
        } catch (Exception e) {
            this.printer.println("Failed to set log destination: " + e.getMessage());
        }

        return this;
    }

    private synchronized void log(LogEvent logEvent) {
        try {
            if (logEvent.getLevel().severity() < this.currentLevel.severity()) {
                return;
            }
            this.context.put(THREAD_NAME_KEY, logEvent.getThreadName());
            var threadName = this.context.get(THREAD_NAME_KEY);
            var formattedMessage = this.formatter.getFormattedString(logEvent, threadName);
            this.printer.write((formattedMessage + LINE_SEPARATOR).getBytes(StandardCharsets.UTF_8));
        } catch (Exception e) {
            reportFormattingFailure(e);
        } finally {
            // TODO: Consider flushing only on certain levels or based on options and not on
            // every log call.
            this.printer.flush();
        }
    }

    private void reportFormattingFailure(Exception failure) {
        try {
            var threadName = Thread.currentThread().getName();
            this.context.put(THREAD_NAME_KEY, threadName);
            var event = new LogEvent(failure.getMessage(), System.currentTimeMillis(), LogLevel.ERROR, threadName);
            var formattedError = this.formatter.getFormattedString(event, threadName);
            this.printer.println(formattedError);
        } catch (Exception alsoFailed) {
            this.printer.println(LogLevel.color(LogLevel.ERROR)
                    + "Failed to format log message: " + failure.getMessage()
                    + LogLevel.color(LogLevel.RESET));
        }
    }

    // TODO: These methods should be refactored to avoid code duplication. Consider using a single method that takes the log level as a parameter.
    @Override
    public synchronized void debug(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.DEBUG) {
            return;
        }
        log(logEvent);
    }

    @Override
    public synchronized void info(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.INFO) {
            return;
        }
        log(logEvent);
    }

    @Override
    public synchronized void warn(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.WARN) {
            return;
        }
        log(logEvent);
    }

    @Override
    public synchronized void error(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.ERROR) {
            return;
        }
        log(logEvent);
    }

    @Override
    public synchronized void trace(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.TRACE) {
            return;
        }
        log(logEvent);
    }

    @Override
    public synchronized void fatal(LogEvent logEvent) {
        if (logEvent.getLevel() != LogLevel.FATAL) {
            return;
        }
        log(logEvent);
    }
}
