/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.FileOutputStream;
import java.io.PrintStream;

public class Logging implements Loggable {

    private Formatable formatter;
    private Context context;

    private PrintStream printer = System.out;
    private boolean ownsPrinter = false;

    public static Loggable getLogger(Formatable formatter, LogOptions options) {
        var logger = new Logging();
        logger.formatter = formatter;
        logger.setOptions(options);
        logger.context = new Context();
        logger.context.put("threadName", Thread.currentThread().getName());
        return logger;
    }

    public Loggable setContext(String key, Object value) {
        this.context.put(key, value);
        return this;
    }

    @Override
    public synchronized Loggable setOptions(LogOptions options) {
        var newFormatter = options.getFormatter();
        if (newFormatter != null) {
            this.formatter = newFormatter;
        }

        var destination = options.getDestination();
        if (destination == null) {
            return this;
        }
        try {
            PrintStream next = switch (destination) {
                case LogDestination.Stdout ignored ->
                    System.out;
                case LogDestination.Stderr ignored ->
                    System.err;
                case LogDestination.LogFile logFile ->
                    new PrintStream(new FileOutputStream(logFile.path(), true), true);
            };
            if (this.ownsPrinter) {
                this.printer.close();
            }
            this.printer = next;
            this.ownsPrinter = destination instanceof LogDestination.LogFile;
        } catch (Exception e) {
            this.printer.println("Failed to set log destination: " + e.getMessage());
        }

        return this;
    }

    private synchronized void log(String message, LogLevel level) {
        try {
            // The thread name travels as an argument, not baked into the
            // message: the format string decides whether and where to show it.
            var threadName = this.context.get("threadName");
            var formattedMessage = this.formatter.getFormattedString(level, message, threadName);
            this.printer.println(formattedMessage);
        } catch (Exception e) {
            reportFormattingFailure(e);
        } finally {
            this.printer.flush();
            this.context.clear();
        }
    }

    private void reportFormattingFailure(Exception failure) {
        try {
            var threadName = Thread.currentThread().getName();
            var formattedError = this.formatter.getFormattedString(LogLevel.ERROR, failure.getMessage(), threadName);
            this.printer.println(formattedError);
        } catch (Exception alsoFailed) {
            this.printer.println(LogLevel.color(LogLevel.ERROR)
                    + "Failed to format log message: " + failure.getMessage()
                    + LogLevel.color(LogLevel.RESET));
        }
    }

    public synchronized void debug(String message) {
        log(message, LogLevel.DEBUG);
    }

    public synchronized void info(String message) {
        log(message, LogLevel.INFO);
    }

    public synchronized void warn(String message) {
        log(message, LogLevel.WARN);
    }

    public synchronized void error(String message) {
        log(message, LogLevel.ERROR);
    }

    public synchronized void trace(String message) {
        log(message, LogLevel.TRACE);
    }

    public synchronized void fatal(String message) {
        log(message, LogLevel.FATAL);
    }
}
