/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.ferizoozoo.thislog;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;

import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

import org.junit.After;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class LoggingTest {
    private static final String ESC = String.valueOf((char) 27);
    private static final String RESET = ESC + "[0m";
    private static final String GREEN = ESC + "[32m";
    private static final String YELLOW = ESC + "[33m";
    private static final String RED = ESC + "[31m";
    private static final String BLUE = ESC + "[34m";

    private static final String NL = System.lineSeparator();

    /** Fixed timestamp for events built directly, to test PatternFormatter on its own. */
    private static final long AT = 1_700_000_000_000L;

    /** A logger name for events built directly, without going through a logger. */
    private static final String NAME = "com.acme.Test";

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    // ---------------------------------------------------------------------
    // Test doubles.
    //
    // The logger builds a LogEvent from the call and hands it to the
    // formatter, then prints whatever string comes back. Unpacking the event
    // here is what makes the level and the message assertable, and the
    // returned string is what should turn up at the destination.
    // ---------------------------------------------------------------------

    private record Call(LogLevel level, String message, long timestamp,
            String threadName, Throwable thrown) {

        static Call of(LogEvent event) {
            return new Call(event.getLevel(), event.getMessage(), event.getTimestamp(),
                    event.getThreadName(), event.getThrown());
        }

        String rendered() {
            return LogLevel.color(level) + "[" + level + "] " + message + RESET;
        }
    }

    private static final class RecordingFormatter implements LogFormatter {
        private final List<Call> calls = new ArrayList<>();

        @Override
        public String format(LogEvent event) {
            var call = Call.of(event);
            calls.add(call);
            return call.rendered();
        }

        Call only() {
            assertEquals("expected exactly one formatted line", 1, calls.size());
            return calls.get(0);
        }
    }

    /** Throws on its first call only, so the logger's recovery path can format. */
    private static final class FailsOnceFormatter implements LogFormatter {
        private final List<Call> calls = new ArrayList<>();
        private boolean armed = true;

        @Override
        public String format(LogEvent event) {
            if (armed) {
                armed = false;
                throw new IllegalStateException("formatter exploded");
            }
            var call = Call.of(event);
            calls.add(call);
            return call.rendered();
        }
    }

    private static final class AlwaysFailsFormatter implements LogFormatter {
        @Override
        public String format(LogEvent event) {
            throw new IllegalStateException("formatter exploded");
        }
    }

    // ---------------------------------------------------------------------
    // Standard streams are redirected for every test, so a logger built with
    // the default destination writes somewhere we can read back.
    // ---------------------------------------------------------------------

    private final PrintStream realStdout = System.out;
    private final PrintStream realStderr = System.err;

    private ByteArrayOutputStream stdout;
    private ByteArrayOutputStream stderr;

    @Before
    public void redirectStandardStreams() {
        LoggingFactory.clear();
        stdout = new ByteArrayOutputStream();
        stderr = new ByteArrayOutputStream();
        System.setOut(new PrintStream(stdout, true, StandardCharsets.UTF_8));
        System.setErr(new PrintStream(stderr, true, StandardCharsets.UTF_8));
    }

    @After
    public void restoreStandardStreams() {
        System.setOut(realStdout);
        System.setErr(realStderr);
    }

    private String stdoutText() {
        return stdout.toString(StandardCharsets.UTF_8);
    }

    private String stderrText() {
        return stderr.toString(StandardCharsets.UTF_8);
    }

    private static LogOptions to(LogDestination destination) {
        return LogOptions.createFromEnvironment().withDestination(destination);
    }

    /**
     * changeOptions replaces the options wholesale rather than merging, so every
     * update that means to keep formatting has to restate the formatter.
     */
    private static LogOptions to(LogDestination destination, LogFormatter formatter) {
        return LogOptions.createFromEnvironment().withDestination(destination).withFormatter(formatter);
    }

    /**
     * A logger on stdout with the given formatter, applied through
     * changeOptions once the logger exists.
     */
    private static Loggable logger(LogFormatter formatter) {
        var log = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        log.changeOptions(with(formatter).withDestination(LogDestination.STDOUT));
        return log;
    }

    private static LogOptions with(LogFormatter formatter) {
        return LogOptions.createFromEnvironment().withFormatter(formatter);
    }

    /** A frame that renders as {@code com.acme.Checkout.complete(Checkout.java:17)}. */
    private static StackTraceElement frame(String type, String method, int line) {
        var simpleName = type.substring(type.lastIndexOf('.') + 1);
        return new StackTraceElement(type, method, simpleName + ".java", line);
    }

    /**
     * Gives a throwable a stack trace of the test's choosing. A real one
     * carries wherever JUnit happened to call from, which is both unreadable in
     * an assertion and free to change; these frames are the whole of what the
     * logger has to render.
     */
    private static <T extends Throwable> T thrownAt(T thrown, StackTraceElement... frames) {
        thrown.setStackTrace(frames);
        return thrown;
    }

    /** One frame on top of a tail two throwables share. */
    private static StackTraceElement[] concat(StackTraceElement top, StackTraceElement[] rest) {
        var frames = new StackTraceElement[rest.length + 1];
        frames[0] = top;
        System.arraycopy(rest, 0, frames, 1, rest.length);
        return frames;
    }

    // ---------------------------------------------------------------------
    // Each level method logs at its own level.
    //
    // The method that was called is now the only thing that decides the
    // level: the logger builds the event, so a caller cannot disagree with it.
    // ---------------------------------------------------------------------

    @Test
    public void infoLogsAtInfoAndCarriesTheMessage() {
        var formatter = new RecordingFormatter();

        logger(formatter).info(() -> "Hello, World!");

        assertEquals(LogLevel.INFO, formatter.only().level());
        assertEquals("Hello, World!", formatter.only().message());
    }

    @Test
    public void warnLogsAtWarn() {
        var formatter = new RecordingFormatter();

        logger(formatter).warn(() -> "Careful");

        assertEquals(LogLevel.WARN, formatter.only().level());
        assertEquals("Careful", formatter.only().message());
    }

    @Test
    public void errorLogsAtError() {
        var formatter = new RecordingFormatter();

        logger(formatter).error(() -> "Boom");

        assertEquals(LogLevel.ERROR, formatter.only().level());
        assertEquals("Boom", formatter.only().message());
    }

    @Test
    public void fatalLogsAtFatal() {
        var formatter = new RecordingFormatter();

        logger(formatter).fatal(() -> "Unrecoverable");

        assertEquals(LogLevel.FATAL, formatter.only().level());
        assertEquals("Unrecoverable", formatter.only().message());
    }

    @Test
    public void debugLogsAtDebugAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).debug(() -> "chatter");

        assertEquals(LogLevel.DEBUG, formatter.only().level());
        assertEquals("chatter", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void traceLogsAtTraceAndIsWritten() {
        var formatter = new RecordingFormatter();

        logger(formatter).trace(() -> "Tracing");

        assertEquals(LogLevel.TRACE, formatter.only().level());
        assertEquals("Tracing", formatter.only().message());
        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void everySixMethodsMapToTheirOwnLevelInOrder() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.trace(() -> "kept");
        log.debug(() -> "kept");
        log.info(() -> "kept");
        log.warn(() -> "kept");
        log.error(() -> "kept");
        log.fatal(() -> "kept");

        assertEquals(
                List.of(LogLevel.TRACE, LogLevel.DEBUG, LogLevel.INFO,
                        LogLevel.WARN, LogLevel.ERROR, LogLevel.FATAL),
                formatter.calls.stream().map(Call::level).toList());
        assertEquals(6, stdoutText().lines().count());
    }

    @Test
    public void theLevelDecidesTheColourTheFormatterCanReachFor() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info(() -> "green");
        log.warn(() -> "yellow");
        log.error(() -> "red");

        assertEquals(GREEN, LogLevel.color(formatter.calls.get(0).level()));
        assertEquals(YELLOW, LogLevel.color(formatter.calls.get(1).level()));
        assertEquals(RED, LogLevel.color(formatter.calls.get(2).level()));
    }

    @Test
    public void theLoggerStampsTheEventItBuilds() {
        var formatter = new RecordingFormatter();

        long before = System.currentTimeMillis();
        logger(formatter).info(() -> "stamped");
        long after = System.currentTimeMillis();

        assertTrue("the timestamp should be taken at the call",
                formatter.only().timestamp() >= before
                        && formatter.only().timestamp() <= after);
        assertEquals(Thread.currentThread().getName(), formatter.only().threadName());
    }

    // ---------------------------------------------------------------------
    // The formatter's return value is what gets written.
    // ---------------------------------------------------------------------

    @Test
    public void theFormattedStringIsWhatReachesTheDestination() {
        var formatter = new RecordingFormatter();

        logger(formatter).info(() -> "on the wire");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void successiveMessagesAccumulateInOrder() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info(() -> "first");
        log.error(() -> "second");

        assertEquals(2, formatter.calls.size());
        assertEquals("first", formatter.calls.get(0).message());
        assertEquals("second", formatter.calls.get(1).message());
        assertEquals(
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(1).rendered() + NL,
                stdoutText());
    }

    // ---------------------------------------------------------------------
    // Destinations.
    // ---------------------------------------------------------------------

    @Test
    public void logsGoToStdoutWhenNoDestinationIsConfigured() {
        var formatter = new RecordingFormatter();

        logger(formatter).info(() -> "to stdout");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
        assertEquals("", stderrText());
    }

    @Test
    public void theStdoutDestinationIsResolvedWhenOptionsAreApplied() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        var replacement = new ByteArrayOutputStream();
        System.setOut(new PrintStream(replacement, true, StandardCharsets.UTF_8));
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "to the new stdout");

        assertEquals("the stream captured at construction should be left alone",
                "", stdoutText());
        assertEquals(formatter.only().rendered() + NL,
                replacement.toString(StandardCharsets.UTF_8));
    }

    @Test
    public void theStderrDestinationDivertsAwayFromStdout() {
        var formatter = new RecordingFormatter();

        var chained1 = logger(formatter);

        chained1.changeOptions(to(LogDestination.STDERR, formatter));

        chained1.info(() -> "to stderr");

        assertEquals(formatter.only().rendered() + NL, stderrText());
        assertEquals("stdout should be untouched once stderr is selected", "", stdoutText());
    }

    @Test
    public void aFileDestinationDivertsAwayFromStdout() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));

        log.info(() -> "to a file");
        log.close();

        assertEquals(formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("stdout should be untouched once a file is selected", "", stdoutText());
    }

    @Test
    public void reopeningAFileDestinationAppendsRatherThanTruncates() throws Exception {
        File sink = tempFolder.newFile();
        var first = new RecordingFormatter();
        var second = new RecordingFormatter();

        var one = logger(first);
        one.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), first));
        one.info(() -> "first");
        one.close();

        var two = logger(second);
        two.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), second));
        two.info(() -> "second");
        two.close();

        assertEquals("opening a file again must not truncate it",
                first.only().rendered() + NL + second.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void switchingAwayFromAFileStopsWritingToIt() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));

        log.info(() -> "to the file");
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "to stdout");

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void optionsThatDoNotNameADestinationUseTheDefault() {
        var formatter = new RecordingFormatter();

        var chained2 = logger(formatter);

        chained2.changeOptions(with(formatter));

        chained2.info(() -> "still on stdout");

        assertEquals("fresh options already carry stdout, so nothing moves",
                formatter.only().rendered() + NL, stdoutText());
        assertEquals("and nothing failed", "", stderrText());
    }

    @Test
    public void anUpdateThatDoesNotNameTheFileLeavesIt() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));
        log.changeOptions(with(formatter));
        log.info(() -> "after the update");
        log.close();

        assertEquals("an update that does not name a file goes back to the default stdout",
                formatter.only().rendered() + NL, stdoutText());
        assertEquals("", Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void loggersDoNotShareADestination() throws Exception {
        File sink = tempFolder.newFile();
        var toFile = new RecordingFormatter();
        var toStdout = new RecordingFormatter();

        var fileLog = logger(toFile);

        fileLog.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), toFile));
        var stdoutLog = logger(toStdout);

        fileLog.info(() -> "to the file");
        stdoutLog.info(() -> "to stdout");
        fileLog.close();

        assertEquals(toFile.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(toStdout.only().rendered() + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // setOptions contract.
    // ---------------------------------------------------------------------

    @Test
    public void anUnusableFileDestinationIsReportedAndThePrinterIsLeftAlone() throws Exception {
        File directory = tempFolder.newFolder();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(directory.getAbsolutePath()), formatter));

        assertTrue("expected a failure notice, got: " + stderrText(),
                stderrText().contains("cannot apply the logging configuration"));

        log.info(() -> "still on stdout");
        assertTrue("logging should carry on where it was",
                stdoutText().endsWith(formatter.only().rendered() + NL));
    }

    // ---------------------------------------------------------------------
    // Runtime reconfiguration.
    //
    // setOptions can be called at any point in a logger's life. What follows
    // pins down what a reconfiguration does to the messages around it: the
    // ones already written, the ones still to come, the stream being left
    // behind, and any other logger that happens to share it.
    // ---------------------------------------------------------------------

    @Test
    public void eachMessageGoesWhereverTheLoggerPointedWhenItWasCalled() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info(() -> "before the move");
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));
        log.info(() -> "while on the file");
        log.close();
        log.changeOptions(to(LogDestination.STDERR, formatter));
        log.info(() -> "while on stderr");
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "back on stdout");

        assertEquals("reconfiguring is not retroactive",
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(3).rendered() + NL,
                stdoutText());
        assertEquals(formatter.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(2).rendered() + NL, stderrText());
    }

    @Test
    public void movingFromOneFileToAnotherLeavesTheFirstCompleteAndUntouched() throws Exception {
        File first = tempFolder.newFile();
        File second = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(first.getAbsolutePath()), formatter));

        log.info(() -> "into the first");
        log.close();
        log.changeOptions(to(LogDestination.file(second.getAbsolutePath()), formatter));
        log.info(() -> "into the second");
        log.close();

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(first.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL,
                Files.readString(second.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void comingBackToAFileAppendsToWhatIsAlreadyThere() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));

        log.info(() -> "first visit");
        log.close();
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "away for a moment");
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));
        log.info(() -> "second visit");
        log.close();

        assertEquals("returning to a file must not truncate it",
                formatter.calls.get(0).rendered() + NL + formatter.calls.get(2).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void aReconfigurationThatFailsReportsToTheDestinationStillInUse() throws Exception {
        File sink = tempFolder.newFile();
        File directory = tempFolder.newFolder();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));
        log.changeOptions(to(LogDestination.file(directory.getAbsolutePath()), formatter));
        log.info(() -> "still on the file");
        log.close();

        assertTrue("the failure is announced on stderr, got: " + stderrText(),
                stderrText().contains("cannot apply the logging configuration"));
        assertEquals("the working destination should survive a failed move",
                formatter.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals("a failed move must not fall back to stdout", "", stdoutText());
    }

    @Test
    public void reselectingTheSameDestinationChangesNothing() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "once only");

        assertEquals(formatter.only().rendered() + NL, stdoutText());
    }

    @Test
    public void movingBetweenTheSharedStreamsNeverClosesThem() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.changeOptions(to(LogDestination.STDERR, formatter));
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.changeOptions(to(LogDestination.STDERR, formatter));
        log.info(() -> "to stderr");
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "to stdout");

        assertFalse("System.out must not be closed on the way past", System.out.checkError());
        assertFalse("System.err must not be closed on the way past", System.err.checkError());
        assertEquals(formatter.calls.get(0).rendered() + NL, stderrText());
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void anOptionsObjectCannotBeEditedOutFromUnderALogger() {
        var formatter = new RecordingFormatter();
        var options = to(LogDestination.STDERR, formatter);
        var log = logger(formatter);
        log.changeOptions(options);

        // The update produces a copy; the logger keeps the object it was given.
        options.withDestination(LogDestination.STDOUT);
        log.info(() -> "still on stderr");

        assertEquals("a caller holding the options must not be able to move the logger",
                formatter.only().rendered() + NL, stderrText());
        assertEquals("", stdoutText());
    }

    @Test
    public void aLoggerBuiltOnAFileCanBeMovedOffItLater() throws Exception {
        File sink = tempFolder.newFile();
        var formatter = new RecordingFormatter();

        var log = LoggingFactory.get(nextLoggerName(), LogOptions.createFromEnvironment());
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), formatter));
        log.info(() -> "into the file");
        log.changeOptions(to(LogDestination.STDOUT, formatter));
        log.info(() -> "out to stdout");

        assertEquals(formatter.calls.get(0).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
        assertEquals(formatter.calls.get(1).rendered() + NL, stdoutText());
    }

    @Test
    public void oneLoggerMovingOffAFileLeavesAnotherStillWritingToIt() throws Exception {
        File sink = tempFolder.newFile();
        var leaving = new RecordingFormatter();
        var staying = new RecordingFormatter();
        var leaves = logger(leaving);

        leaves.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), leaving));
        var stays = logger(staying);
        stays.changeOptions(to(LogDestination.file(sink.getAbsolutePath()), staying));

        leaves.info(() -> "from the one that leaves");
        leaves.close();
        stays.info(() -> "from the one that stays");
        stays.info(() -> "after the other one left");
        stays.close();

        assertEquals(
                leaving.only().rendered() + NL
                        + staying.calls.get(0).rendered() + NL
                        + staying.calls.get(1).rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    // ---------------------------------------------------------------------
    // Runtime configuration of the formatter.
    // ---------------------------------------------------------------------

    @Test
    public void aFormatterSetAtRuntimeReplacesTheOneTheLoggerWasBuiltWith() {
        var original = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var log = logger(original);

        log.info(() -> "through the original");
        log.changeOptions(with(replacement));
        log.info(() -> "through the replacement");

        assertEquals("through the original", original.only().message());
        assertEquals("through the replacement", replacement.only().message());
        assertEquals(original.only().rendered() + NL + replacement.only().rendered() + NL,
                stdoutText());
    }

    @Test
    public void theFormatterAndTheDestinationCanMoveInTheSameCall() throws Exception {
        File sink = tempFolder.newFile();
        var original = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var log = logger(original);

        log.info(() -> "original, on stdout");
        log.changeOptions(with(replacement)
                .withDestination(LogDestination.file(sink.getAbsolutePath())));
        log.info(() -> "replacement, on the file");
        log.close();

        assertEquals(original.only().rendered() + NL, stdoutText());
        assertEquals(replacement.only().rendered() + NL,
                Files.readString(sink.toPath(), StandardCharsets.UTF_8));
    }

    @Test
    public void optionsThatDoNotNameAFormatterFallBackToTheDefault() {
        var formatter = new RecordingFormatter();

        var chained3 = logger(formatter);

        chained3.changeOptions(to(LogDestination.STDERR));

        chained3.info(() -> "the formatter went with the options it replaced");

        assertEquals("the options are replaced wholesale, so the old formatter is dropped",
                List.of(), formatter.calls);
        assertEquals("what replaced it is the default pattern, not nothing",
                "the formatter went with the options it replaced" + NL, stderrText());
    }

    @Test
    public void swappingFormattersChangesTheShapeOfTheLinesThatFollow() {
        var log = logger(PatternFormatter.create("[%s]"));

        log.info(() -> "first");
        log.changeOptions(with(PatternFormatter.create("<%s>")));
        log.info(() -> "second");

        assertEquals("the swap must not reach back over what was already written",
                "[first]" + NL + "<second>" + NL, stdoutText());
    }

    @Test
    public void aFormatterSetAtRuntimeIsGivenTheWholeEvent() {
        var replacement = new RecordingFormatter();

        var chained4 = logger(new RecordingFormatter());

        chained4.changeOptions(with(replacement));

        chained4.warn(() -> "Careful");

        assertEquals(LogLevel.WARN, replacement.only().level());
        assertEquals("Careful", replacement.only().message());
        assertEquals(Thread.currentThread().getName(), replacement.only().threadName());
    }

    @Test
    public void swappingInAWorkingFormatterRecoversALoggerThatCouldNotFormat() {
        var replacement = new RecordingFormatter();
        var log = logger(new AlwaysFailsFormatter());

        log.info(() -> "never formatted");
        log.changeOptions(with(replacement));
        log.info(() -> "formatted at last");

        assertEquals(
                RED + "Failed to format log message: "
                        + "java.lang.IllegalStateException: formatter exploded" + RESET + NL
                        + replacement.only().rendered() + NL,
                stdoutText());
    }

    @Test
    public void swappingInABrokenFormatterIsStillNotFatal() {
        var log = logger(new RecordingFormatter());

        log.changeOptions(with(new AlwaysFailsFormatter()));
        log.info(() -> "first");
        log.error(() -> "second");

        assertEquals("the caller should keep running either way", 2, stdoutText().lines().count());
    }

    @Test
    public void aFormatterSwappedOnACopyNeverReachesTheLogger() {
        var inUse = new RecordingFormatter();
        var neverApplied = new RecordingFormatter();
        var options = with(inUse);
        var log = logger(new RecordingFormatter());
        log.changeOptions(options);

        options.withFormatter(neverApplied);
        log.info(() -> "through the formatter the logger was given");

        assertEquals("the logger formats through the options it holds, not a later copy",
                "through the formatter the logger was given", inUse.only().message());
        assertEquals(List.of(), neverApplied.calls);
    }

    @Test
    public void swappingOneLoggersFormatterLeavesAnotherLoggerOnTheOldOne() {
        var shared = new RecordingFormatter();
        var replacement = new RecordingFormatter();
        var swapped = logger(shared);
        var untouched = logger(shared);

        swapped.changeOptions(with(replacement));

        swapped.info(() -> "through the replacement");
        untouched.info(() -> "still through the shared one");

        assertEquals("through the replacement", replacement.only().message());
        assertEquals("still through the shared one", shared.only().message());
    }

    // ---------------------------------------------------------------------
    // A formatter that throws must not take the logger down with it.
    // ---------------------------------------------------------------------

    @Test
    public void aFailingFormatterIsReportedThroughTheErrorPath() {
        var formatter = new FailsOnceFormatter();

        logger(formatter).info(() -> "never formatted");

        assertEquals(1, formatter.calls.size());
        Call recovery = formatter.calls.get(0);
        assertEquals("the recovery line is reported at ERROR whatever failed",
                LogLevel.ERROR, recovery.level());
        assertEquals("Failed to format log message", recovery.message());
        assertEquals("the failure travels on the event rather than inside its message",
                "formatter exploded", recovery.thrown().getMessage());
        assertTrue("expected the rendered line first, got: " + stdoutText(),
                stdoutText().startsWith(recovery.rendered() + NL));
    }

    @Test
    public void theRecoveryLineCarriesTheFailureOnlyOnTheEvent() {
        var formatter = new FailsOnceFormatter();

        logger(formatter).info(() -> "never formatted");

        // reportFormattingFailure prints just the formatted line, so what the
        // reader sees depends entirely on whether their LogFormatter reaches for
        // event.getThrown(). The recording one here does not.
        assertEquals(formatter.calls.get(0).rendered() + NL, stdoutText());
        assertEquals("formatter exploded", formatter.calls.get(0).thrown().getMessage());
    }

    @Test
    public void aFormatterThatAlwaysFailsFallsBackToAPlainNotice() {
        logger(new AlwaysFailsFormatter()).info(() -> "never formatted");

        // The last-ditch branch uses toString(), so the exception type survives
        // even when getMessage() would have been null.
        assertEquals(
                RED + "Failed to format log message: "
                        + "java.lang.IllegalStateException: formatter exploded" + RESET + NL,
                stdoutText());
    }

    @Test
    public void aBrokenFormatterNeverStopsTheCaller() {
        var log = logger(new AlwaysFailsFormatter());

        log.info(() -> "first");
        log.error(() -> "second");

        assertEquals("the caller should keep running either way", 2, stdoutText().lines().count());
    }

    // ---------------------------------------------------------------------
    // Exceptions.
    //
    // A throwable is the application's failure, not the logger's: the caller
    // hands over the object rather than a string, so the logger can render the
    // frames and the cause chain, and can decline to render anything at all
    // when the line is suppressed.
    // ---------------------------------------------------------------------

    @Test
    public void theExceptionReachesTheFormatterOnTheEvent() {
        var formatter = new RecordingFormatter();
        var boom = new IllegalStateException("payment declined");

        logger(formatter).error(() -> "payment failed", boom);

        assertSame(boom, formatter.only().thrown());
        assertEquals(LogLevel.ERROR, formatter.only().level());
        assertEquals("payment failed", formatter.only().message());
    }

    @Test
    public void theExceptionIsPrintedBeneathTheLineItBelongsTo() {
        var formatter = new RecordingFormatter();
        var boom = thrownAt(new IllegalStateException("payment declined"),
                frame("com.acme.Payments", "charge", 42));

        logger(formatter).error(() -> "payment failed", boom);

        assertEquals(formatter.only().rendered() + NL
                + "java.lang.IllegalStateException: payment declined" + NL
                + "\tat com.acme.Payments.charge(Payments.java:42)" + NL,
                stdoutText());
    }

    @Test
    public void anExceptionRendersEveryFrameItCarries() {
        var boom = thrownAt(new IllegalStateException("payment declined"),
                frame("com.acme.Payments", "charge", 42),
                frame("com.acme.Checkout", "complete", 17),
                frame("com.acme.Main", "main", 8));

        logger(PatternFormatter.create("%s")).error(() -> "payment failed", boom);

        assertEquals("payment failed" + NL
                + "java.lang.IllegalStateException: payment declined" + NL
                + "\tat com.acme.Payments.charge(Payments.java:42)" + NL
                + "\tat com.acme.Checkout.complete(Checkout.java:17)" + NL
                + "\tat com.acme.Main.main(Main.java:8)" + NL,
                stdoutText());
    }

    @Test
    public void aRealExceptionCarriesTheFrameItWasThrownFrom() {
        // The frames the other tests plant are the test's own; this is the one
        // that proves a throwable arriving from a real call site keeps the
        // trace the JVM gave it.
        logger(PatternFormatter.create("%s")).error(() -> "load failed",
                new IllegalStateException("could not load order 4711"));

        assertTrue("the throwing frame belongs in the output, got: " + stdoutText(),
                stdoutText().contains("\tat io.github.ferizoozoo.thislog.LoggingTest"
                        + ".aRealExceptionCarriesTheFrameItWasThrownFrom"));
    }

    @Test
    public void anExceptionWithNoFramesRendersJustItsLine() {
        var boom = thrownAt(new IllegalStateException("no trace to give"));

        logger(PatternFormatter.create("%s")).error(() -> "load failed", boom);

        assertEquals("load failed" + NL
                + "java.lang.IllegalStateException: no trace to give" + NL,
                stdoutText());
    }

    @Test
    public void aWrappedExceptionShowsItsWholeCauseChain() {
        var main = frame("com.acme.Main", "main", 8);
        var cause = thrownAt(new ArrayIndexOutOfBoundsException("Index 3 out of bounds for length 0"),
                frame("com.acme.Orders", "load", 91), main);
        var wrapper = thrownAt(new IllegalStateException("could not load order 4711", cause),
                frame("com.acme.Checkout", "complete", 17), main);

        logger(PatternFormatter.create("%s")).error(() -> "load failed", wrapper);

        assertEquals("load failed" + NL
                + "java.lang.IllegalStateException: could not load order 4711" + NL
                + "\tat com.acme.Checkout.complete(Checkout.java:17)" + NL
                + "\tat com.acme.Main.main(Main.java:8)" + NL
                + "Caused by: java.lang.ArrayIndexOutOfBoundsException: "
                + "Index 3 out of bounds for length 0" + NL
                + "\tat com.acme.Orders.load(Orders.java:91)" + NL
                + "\t... 1 more" + NL,
                stdoutText());
    }

    @Test
    public void aCauseRepeatsOnlyTheFramesTheWrapperDoesNotAlreadyShow() {
        var shared = new StackTraceElement[] {
                frame("com.acme.Checkout", "complete", 17),
                frame("com.acme.Server", "dispatch", 204),
                frame("com.acme.Main", "main", 8),
        };
        var cause = thrownAt(new IllegalArgumentException("price was negative"),
                concat(frame("com.acme.Pricing", "price", 66), shared));
        var wrapper = thrownAt(new IllegalStateException("could not price the basket", cause), shared);

        logger(PatternFormatter.create("%s")).error(() -> "checkout failed", wrapper);

        // The three frames the two have in common are printed once, under the
        // wrapper, and counted under the cause.
        assertEquals("checkout failed" + NL
                + "java.lang.IllegalStateException: could not price the basket" + NL
                + "\tat com.acme.Checkout.complete(Checkout.java:17)" + NL
                + "\tat com.acme.Server.dispatch(Server.java:204)" + NL
                + "\tat com.acme.Main.main(Main.java:8)" + NL
                + "Caused by: java.lang.IllegalArgumentException: price was negative" + NL
                + "\tat com.acme.Pricing.price(Pricing.java:66)" + NL
                + "\t... 3 more" + NL,
                stdoutText());
    }

    @Test
    public void aCauselessExceptionAddsNoCausedByLine() {
        var boom = thrownAt(new IllegalStateException("could not load order 4711"),
                frame("com.acme.Orders", "load", 91));

        logger(PatternFormatter.create("%s")).error(() -> "load failed", boom);

        assertEquals("load failed" + NL
                + "java.lang.IllegalStateException: could not load order 4711" + NL
                + "\tat com.acme.Orders.load(Orders.java:91)" + NL,
                stdoutText());
    }

    @Test
    public void aSuppressedExceptionIsRenderedUnderTheOneItGaveWayTo() {
        var main = frame("com.acme.Main", "main", 8);
        var boom = thrownAt(new IllegalStateException("write failed"),
                frame("com.acme.Export", "write", 30), main);
        boom.addSuppressed(thrownAt(new IllegalStateException("and the file would not close"),
                frame("com.acme.Export", "close", 55), main));

        logger(PatternFormatter.create("%s")).error(() -> "export failed", boom);

        // try-with-resources produces these, and an indent is what separates
        // the failure that was kept from the one that gave way to it.
        assertEquals("export failed" + NL
                + "java.lang.IllegalStateException: write failed" + NL
                + "\tat com.acme.Export.write(Export.java:30)" + NL
                + "\tat com.acme.Main.main(Main.java:8)" + NL
                + "\tSuppressed: java.lang.IllegalStateException: and the file would not close" + NL
                + "\t\tat com.acme.Export.close(Export.java:55)" + NL
                + "\t\t... 1 more" + NL,
                stdoutText());
    }

    @Test
    public void aTraceIsRenderedExactlyAsPrintStackTraceWouldRenderIt() {
        // The frames the tests above plant are readable but synthetic. This one
        // takes a real throwable -- deep frames, two suppressed exceptions, one
        // of them with a cause of its own -- and holds the whole rendering
        // against the JDK's, which is the format every Java reader already
        // knows. It is also the only check that the elision counts are right
        // for a trace nobody chose.
        var cause = new IllegalArgumentException("price was negative");
        var wrapper = new IllegalStateException("could not price the basket", cause);
        wrapper.addSuppressed(new IllegalStateException("and the session would not close",
                new java.io.IOException("socket already shut")));
        wrapper.addSuppressed(new IllegalStateException("and the cart would not unlock"));
        var boom = new RuntimeException("checkout failed for order 4711", wrapper);

        var expected = new ByteArrayOutputStream();
        try (var into = new PrintStream(expected, true, StandardCharsets.UTF_8)) {
            boom.printStackTrace(into);
        }

        logger(PatternFormatter.create("%s")).error(() -> "", boom);

        // The pattern writes the empty message and its line break first.
        assertEquals(NL + expected.toString(StandardCharsets.UTF_8), stdoutText());
    }

    @Test
    public void aCyclicCauseChainTerminatesRatherThanSpinning() {
        var main = frame("com.acme.Main", "main", 8);
        var first = thrownAt(new IllegalStateException("first"),
                frame("com.acme.One", "call", 11), main);
        var second = thrownAt(new IllegalStateException("second", first),
                frame("com.acme.Two", "call", 22), main);
        first.initCause(second);

        logger(PatternFormatter.create("%s")).error(() -> "tangled", second);

        assertEquals("tangled" + NL
                + "java.lang.IllegalStateException: second" + NL
                + "\tat com.acme.Two.call(Two.java:22)" + NL
                + "\tat com.acme.Main.main(Main.java:8)" + NL
                + "Caused by: java.lang.IllegalStateException: first" + NL
                + "\tat com.acme.One.call(One.java:11)" + NL
                + "\t... 1 more" + NL
                + "Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: second]" + NL,
                stdoutText());
    }

    @Test
    public void everyLevelMethodAcceptsAThrowable() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var boom = new IllegalStateException("boom");

        log.trace(() -> "t", boom);
        log.debug(() -> "d", boom);
        log.info(() -> "i", boom);
        log.warn(() -> "w", boom);
        log.error(() -> "e", boom);
        log.fatal(() -> "f", boom);

        assertEquals(
                List.of(LogLevel.TRACE, LogLevel.DEBUG, LogLevel.INFO,
                        LogLevel.WARN, LogLevel.ERROR, LogLevel.FATAL),
                formatter.calls.stream().map(Call::level).toList());
        assertEquals(Collections.nCopies(6, boom),
                formatter.calls.stream().map(Call::thrown).toList());
    }

    @Test
    public void aNullThrowableLogsExactlyLikeTheOneArgumentCall() {
        var passingNull = new RecordingFormatter();
        logger(passingNull).info(() -> "same either way", null);
        String withNull = stdoutText();

        stdout.reset();
        var omitting = new RecordingFormatter();
        logger(omitting).info(() -> "same either way");

        assertNull(passingNull.only().thrown());
        assertNull(omitting.only().thrown());
        assertEquals(withNull, stdoutText());
    }

    @Test
    public void aSuppressedCallNeverRendersItsException() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setCurrentLogLevel(LogLevel.ERROR);
        log.debug(() -> "expensive to render", new IllegalStateException("never rendered"));

        assertEquals("rendering a stack trace is exactly the work a threshold should save",
                List.of(), formatter.calls);
        assertEquals("", stdoutText());
    }

    // ---------------------------------------------------------------------
    // The message is a Supplier, so building it is the logger's decision.
    //
    // This is the whole point of the deferred message: below the threshold
    // the lambda body must never run, so a caller pays nothing for a line
    // that is going to be dropped.
    // ---------------------------------------------------------------------

    /** Counts how often it was asked for its message. */
    private static final class CountingSupplier implements Supplier<String> {
        private final AtomicInteger calls = new AtomicInteger();

        @Override
        public String get() {
            calls.incrementAndGet();
            return "built " + calls.get() + " time(s)";
        }
    }

    @Test
    public void aSuppressedMessageIsNeverBuilt() {
        var message = new CountingSupplier();
        var log = logger(new RecordingFormatter());

        log.setCurrentLogLevel(LogLevel.ERROR);
        log.debug(message);

        assertEquals("a dropped line must cost nothing to produce", 0, message.calls.get());
        assertEquals("", stdoutText());
    }

    @Test
    public void aMessageAtOrAboveTheThresholdIsBuiltExactlyOnce() {
        var message = new CountingSupplier();
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.setCurrentLogLevel(LogLevel.INFO);
        log.warn(message);

        assertEquals("the supplier must not be consulted twice", 1, message.calls.get());
        assertEquals("built 1 time(s)", formatter.only().message());
    }

    @Test
    public void loweringTheThresholdStartsBuildingMessagesAgain() {
        var message = new CountingSupplier();
        var log = logger(new RecordingFormatter());

        log.setCurrentLogLevel(LogLevel.ERROR);
        log.debug(message);
        log.setCurrentLogLevel(LogLevel.TRACE);
        log.debug(message);

        assertEquals("only the call made under the lower threshold should build",
                1, message.calls.get());
    }

    @Test
    public void aSuppressedMessageWithAThrowableIsNeverBuiltEither() {
        var message = new CountingSupplier();
        var log = logger(new RecordingFormatter());

        log.setCurrentLogLevel(LogLevel.ERROR);
        log.debug(message, new IllegalStateException("never rendered"));

        assertEquals(0, message.calls.get());
        assertEquals("", stdoutText());
    }

    @Test
    public void aFailingMessageSupplierDoesNotReachTheCaller() {
        var log = logger(new RecordingFormatter());

        // Reaching the next line at all is the assertion: a logging call is
        // usually made from a failure path, and must not add a second failure.
        log.info(() -> {
            throw new IllegalStateException("could not build the message");
        });

        assertTrue("the logger should carry on afterwards", log.isEnabled(LogLevel.INFO));
    }

    @Test
    public void aMessageThatCannotBeBuiltStillWritesItsThrowable() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);
        var real = new IllegalStateException("payment declined");

        log.error(() -> {
            throw new NullPointerException("customer was null");
        }, real);

        assertTrue("the line should say the message could not be built, got: "
                        + formatter.only().message(),
                formatter.only().message().contains("message supplier failed"));
        assertSame("the error being reported must survive a message that would not build",
                real, formatter.only().thrown());
    }

    @Test
    public void aNullMessageSupplierIsReportedRatherThanThrown() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        log.info((Supplier<String>) null);

        assertTrue("no message at all is reported the same way as one that would not build, got: "
                        + formatter.only().message(),
                formatter.only().message().contains("message supplier failed"));
    }

    @Test
    public void theGeneralLogMethodIsUsableDirectly() {
        var formatter = new RecordingFormatter();

        logger(formatter).log(LogLevel.WARN, () -> "through the general method", null);

        assertEquals(LogLevel.WARN, formatter.only().level());
        assertEquals("through the general method", formatter.only().message());
    }

    // ---------------------------------------------------------------------
    // Options and destinations as values.
    // ---------------------------------------------------------------------

    @Test
    public void freshOptionsCarryTheEnvironmentDefaults() {
        var fresh = LogOptions.createFromEnvironment();

        assertEquals("no LOG_DESTINATION is set for the test JVM, so stdout is the default",
                LogDestination.STDOUT, fresh.getDestination());
        assertNotNull("and a formatter comes with it", fresh.getFormatter());
    }

    @Test
    public void anUpdateReturnsACopyAndLeavesTheOriginalAlone() {
        var options = LogOptions.createFromEnvironment();

        var moved = options.withDestination(LogDestination.STDERR);

        assertNotSame("an update must not hand back the object it was called on",
                options, moved);
        assertEquals(LogDestination.STDERR, moved.getDestination());
        assertEquals("the original is untouched",
                LogDestination.STDOUT, options.getDestination());
    }

    @Test
    public void changingOnlyTheDestinationKeepsTheFormatterInUse() {
        var formatter = new RecordingFormatter();
        var log = logger(formatter);

        // The logger's own options are the base, so the formatter it is
        // already using comes along rather than reverting to the default.
        log.changeOptions(log.getOptions().withDestination(LogDestination.STDERR));
        log.info(() -> "moved, and still formatted the same way");

        assertSame("a partial update must not reach past the field it names",
                formatter, log.getOptions().getFormatter());
        assertEquals(formatter.only().rendered() + NL, stderrText());
        assertEquals("", stdoutText());
    }

    @Test
    public void anUpdateCarriesOverTheFieldItDoesNotName() {
        var formatter = new RecordingFormatter();
        var options = LogOptions.createFromEnvironment().withFormatter(formatter);

        var moved = options.withDestination(LogDestination.STDERR);

        assertSame("naming a destination must not cost the formatter",
                formatter, moved.getFormatter());
        assertSame("and naming a formatter must not cost the destination",
                LogDestination.STDERR, moved.withFormatter(formatter).getDestination());
    }

    @Test
    public void aFileDestinationCarriesItsPathAndComparesByValue() {
        var one = LogDestination.file("/var/log/a.log");
        var same = LogDestination.file("/var/log/a.log");
        var other = LogDestination.file("/var/log/b.log");

        assertEquals("/var/log/a.log", ((LogDestination.LogFile) one).path());
        assertEquals(one, same);
        assertNotEquals(one, other);
    }

    @Test
    public void theSharedStreamDestinationsAreDistinct() {
        assertTrue(LogDestination.STDOUT instanceof LogDestination.Stdout);
        assertTrue(LogDestination.STDERR instanceof LogDestination.Stderr);
        assertNotEquals(LogDestination.STDOUT, LogDestination.STDERR);
    }

    // ---------------------------------------------------------------------
    // The shipped PatternFormatter, exercised directly.
    // ---------------------------------------------------------------------

    @Test
    public void theShippedFormatterFillsItsConversionWithTheMessage() {
        assertEquals("[Careful]",
                PatternFormatter.create("[%s]")
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT, NAME)));
    }

    @Test
    public void theShippedFormatterHonoursTheFormatItWasBuiltWith() {
        assertEquals("<<Careful>>",
                PatternFormatter.create("<<%s>>")
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT, NAME)));
    }

    @Test
    public void theShippedFormatterAddsNoColourOfItsOwn() {
        var log = logger(PatternFormatter.create("%s"));

        log.warn(() -> "careful");
        log.error(() -> "boom");

        assertEquals("careful" + NL + "boom" + NL, stdoutText());
    }

    @Test
    public void theColouredWrapperColoursByTheLevelTheEventCarries() {
        var log = logger(LogFormatter.colored(PatternFormatter.create("%s")));

        log.warn(() -> "careful");
        log.error(() -> "boom");

        assertEquals(YELLOW + "careful" + RESET + NL + RED + "boom" + RESET + NL, stdoutText());
    }

    @Test
    public void theColouredWrapperKeepsWhateverLayoutItWraps() {
        assertEquals(YELLOW + "[Careful]" + RESET,
                LogFormatter.colored(PatternFormatter.create("[%s]"))
                        .format(LogEvent.create("Careful", LogLevel.WARN, AT, NAME)));
    }

    @Test
    public void theDefaultFormatRendersTheMessageAndNothingElse() {
        assertEquals("Hello, World!",
                PatternFormatter.create(PatternFormatter.DEFAULT_PATTERN)
                        .format(LogEvent.create("Hello, World!", LogLevel.INFO, AT, NAME)));
    }

    // ---------------------------------------------------------------------
    // The pattern language. A conversion is rendered only when the pattern
    // names it, so the default stays a bare message.
    // ---------------------------------------------------------------------

    /** The event the pattern tests render, fixed in every field. */
    private static LogEvent theEvent() {
        return LogEvent.create("Careful", LogLevel.WARN, AT, NAME);
    }

    private static String rendered(String pattern) {
        return PatternFormatter.create(pattern).format(theEvent());
    }

    @Test
    public void everyNameForTheMessageRendersTheMessage() {
        for (String conversion : List.of("%m", "%msg", "%message", "%s")) {
            assertEquals(conversion + " should render the message",
                    "Careful", rendered(conversion));
        }
    }

    @Test
    public void theLevelTheLoggerNameAndTheThreadAreReachableFromAPattern() {
        assertEquals("WARN", rendered("%level"));
        assertEquals(NAME, rendered("%logger"));
        assertEquals(Thread.currentThread().getName(), rendered("%thread"));
    }

    @Test
    public void theTimestampIsRenderedThroughTheOneDateFormat() {
        var expected = DateTimeFormatter.ofPattern(PatternFormatter.DEFAULT_DATE_PATTERN)
                .withZone(ZoneId.systemDefault())
                .format(Instant.ofEpochMilli(AT));

        assertEquals(expected, rendered("%date"));
    }

    @Test
    public void aLongerConversionIsPreferredToOneThatStartsTheSameWay() {
        // "%message" must not be read as "%m" followed by the literal "essage".
        assertEquals("Careful", rendered("%message"));
        assertEquals("Careful", rendered("%msg"));
    }

    @Test
    public void aLayoutCanSpendEverythingTheEventCarriesInOnePattern() {
        var clock = DateTimeFormatter.ofPattern(PatternFormatter.DEFAULT_DATE_PATTERN)
                .withZone(ZoneId.systemDefault())
                .format(Instant.ofEpochMilli(AT));

        assertEquals(clock + " WARN [" + Thread.currentThread().getName() + "] " + NAME + " - Careful",
                rendered("%date %level [%thread] %logger - %m"));
    }

    @Test
    public void aPatternIsCompiledOnceAndRendersTheSameLineEveryTime() {
        var formatter = PatternFormatter.create("%level: %m");

        assertEquals("WARN: Careful", formatter.format(theEvent()));
        assertEquals("the compiled pattern is not consumed by rendering",
                "WARN: Careful", formatter.format(theEvent()));
    }

    @Test
    public void aPatternCanPutALineSeparatorInsideOneEvent() {
        assertEquals("WARN" + NL + "Careful", rendered("%level%n%m"));
    }

    @Test
    public void aPatternMadeOnlyOfLiteralTextRendersThatText() {
        assertEquals("nothing to see here", rendered("nothing to see here"));
    }

    @Test
    public void theFormatterKeepsThePatternItWasBuiltWith() {
        assertEquals("[%level] %m", PatternFormatter.create("[%level] %m").pattern());
    }

    @Test
    public void theDefaultFormatCarriesAMessageAllTheWayToTheDestination() {
        logger(PatternFormatter.create(PatternFormatter.DEFAULT_PATTERN)).warn(() -> "Careful");

        assertEquals("Careful" + NL, stdoutText());
    }

    @Test
    public void aFileDestinationGetsNoEscapeSequencesFromTheDefaultFormat() throws Exception {
        // Colour belongs to the destination, so an uncoloured formatter is what
        // keeps escape sequences out of a file someone will later grep.
        File sink = tempFolder.newFile();
        var plain = PatternFormatter.create(PatternFormatter.DEFAULT_PATTERN);
        var log = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(plain));
        log.info(() -> "user signed in");
        log.close();

        var written = Files.readString(sink.toPath());
        assertFalse("no escape sequences belong in a file, got: " + written,
                written.contains(ESC));
        assertEquals("user signed in" + NL, written);
    }

    @Test
    public void aFormatterBuiltWithoutAPatternIsRejectedAtTheConstructor() {
        assertThrows(NullPointerException.class, () -> PatternFormatter.create(null));
    }

    @Test
    public void aPercentThatNamesNoConversionIsJustAPercent() {
        // The pattern that used to send every single line down the recovery path.
        // There is no escape to remember: a % the table does not name is literal.
        logger(PatternFormatter.create("50% done: %s")).info(() -> "reindexing");

        assertEquals("50% done: reindexing" + NL, stdoutText());
    }

    @Test
    public void aPatternEndingInAPercentKeepsIt() {
        assertEquals("100%", rendered("100%"));
    }

    @Test
    public void aConversionThatDoesNotExistIsLeftAsWritten() {
        assertEquals("Careful %nonsense", rendered("%s %nonsense"));
    }

    @Test
    public void aPercentInTheMessageIsNeverReadAsAConversion() {
        // The message is appended into the line, not substituted into the
        // pattern, so nothing rescans it.
        assertEquals("100%s of users",
                PatternFormatter.create("%m")
                        .format(LogEvent.create("100%s of users", LogLevel.WARN, AT, NAME)));
    }

    @Test
    public void theShippedFormatterWritesItsLineToTheDestination() {
        logger(PatternFormatter.create("%s")).info(() -> "Hello, World!");

        assertEquals("Hello, World!" + NL, stdoutText());
    }

    @Test
    public void theShippedFormatterEmitsOneLinePerCall() {
        var log = logger(PatternFormatter.create("%s"));

        log.info(() -> "first");
        log.warn(() -> "second");
        log.debug(() -> "third");

        assertEquals(3, stdoutText().lines().count());
    }

    @Test
    public void theShippedFormatterLeavesTheTimestampAndThreadNameToOtherLayouts() {
        // A conversion costs nothing unless the pattern names it. "%s" names only
        // the message, so a pattern that wants a word gets a word -- the rest of
        // the event stays on the event.
        logger(PatternFormatter.create("%s")).info(() -> "terse");

        assertEquals("terse" + NL, stdoutText());
    }

    // ---------------------------------------------------------------------
    // Colours are a property of the level itself.
    // ---------------------------------------------------------------------

    @Test
    public void everyLevelMapsToAColour() {
        assertEquals(BLUE, LogLevel.color(LogLevel.TRACE));
        assertEquals(BLUE, LogLevel.color(LogLevel.DEBUG));
        assertEquals(GREEN, LogLevel.color(LogLevel.INFO));
        assertEquals(YELLOW, LogLevel.color(LogLevel.WARN));
        assertEquals(RED, LogLevel.color(LogLevel.ERROR));
        assertEquals(RED, LogLevel.color(LogLevel.FATAL));
    }

    @Test
    public void theResetIsItsOwnThingRatherThanTheColourOfALevel() {
        assertEquals("the reset used to be reachable only as color(OFF)",
                RESET, LogLevel.reset());
    }

    @Test
    public void everyLevelIsSomethingThatCanBeLoggedAt() {
        // OFF is a threshold, not a level, so it is no longer in the enum and
        // log(OFF, ...) no longer compiles.
        for (LogLevel level : LogLevel.values()) {
            assertNotEquals("a level worth logging at needs a colour of its own",
                    RESET, LogLevel.color(level));
        }
    }

    @Test
    public void aColouredMessageIsWrappedInItsLevelAndClosedWithTheReset() {
        assertEquals(YELLOW + "careful" + RESET,
                LogLevel.coloredMessage("careful", LogLevel.WARN));
    }

    @Test
    public void severityIncreasesWithTheLevel() {
        assertTrue(LogLevel.TRACE.severity() < LogLevel.DEBUG.severity());
        assertTrue(LogLevel.DEBUG.severity() < LogLevel.INFO.severity());
        assertTrue(LogLevel.INFO.severity() < LogLevel.WARN.severity());
        assertTrue(LogLevel.WARN.severity() < LogLevel.ERROR.severity());
        assertTrue(LogLevel.ERROR.severity() < LogLevel.FATAL.severity());
    }

    // ---------------------------------------------------------------------
    // Concurrency.
    //
    // The level methods are no longer synchronized -- only the write is -- so
    // formatting now happens off the lock and several threads can be inside a
    // formatter at once. What must still hold is that a line reaches the
    // destination whole: nothing spliced into the middle of it, nothing lost,
    // nothing written twice.
    // ---------------------------------------------------------------------

    @Test
    public void concurrentLoggingWritesEveryLineWholeAndExactlyOnce() throws Exception {
        File sink = tempFolder.newFile();
        var messageOnly = PatternFormatter.create("%s");
        var log = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        log.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(messageOnly));

        int threadCount = 4;
        int perThread = 50;
        var start = new CountDownLatch(1);
        var workers = new ArrayList<Thread>();
        var expected = new ArrayList<String>();

        for (int t = 0; t < threadCount; t++) {
            String tag = "worker-" + t;
            for (int i = 0; i < perThread; i++) {
                expected.add(line(tag, i));
            }
            var worker = new Thread(() -> {
                await(start);
                for (int i = 0; i < perThread; i++) {
                    int n = i;
                    log.info(() -> line(tag, n));
                }
            }, tag);
            workers.add(worker);
            worker.start();
        }

        start.countDown();
        for (Thread worker : workers) {
            worker.join(10_000);
            assertFalse(worker.getName() + " did not finish", worker.isAlive());
        }
        log.close();

        List<String> written = Files.readAllLines(sink.toPath(), StandardCharsets.UTF_8);
        assertEquals(threadCount * perThread, written.size());

        Collections.sort(expected);
        Collections.sort(written);
        assertEquals("every line must arrive whole and exactly once", expected, written);
    }

    // ---------------------------------------------------------------------
    // One stream per file.
    //
    // The concurrency cases below exercise the result; these pin the mechanism,
    // which is the part that can regress silently. A second stream over the
    // same file is a second buffer, and two buffers flush on their own
    // boundaries rather than on line boundaries.
    // ---------------------------------------------------------------------

    @Test
    public void onePathHandsOutOneStreamHoweverManyAskForIt() throws Exception {
        File sink = tempFolder.newFile();
        var path = sink.getAbsolutePath();

        var first = FileStreams.acquire(path);
        var second = FileStreams.acquire(path);
        try {
            assertSame("a file must have exactly one open stream", first, second);
        } finally {
            FileStreams.release(path);
            FileStreams.release(path);
        }
    }

    @Test
    public void twoSpellingsOfOnePathAreStillOnePath() throws Exception {
        File sink = tempFolder.newFile();
        var direct = sink.getAbsolutePath();
        var roundabout = sink.getParentFile().getAbsolutePath()
                + File.separator + "." + File.separator + sink.getName();

        var first = FileStreams.acquire(direct);
        var second = FileStreams.acquire(roundabout);
        try {
            assertSame("the registry key has to be canonical, or the sharing buys nothing",
                    first, second);
        } finally {
            FileStreams.release(direct);
            FileStreams.release(roundabout);
        }
    }

    @Test
    public void theFileIsClosedOnlyWhenTheLastHolderLetsGo() throws Exception {
        File sink = tempFolder.newFile();
        var path = sink.getAbsolutePath();

        var stream = FileStreams.acquire(path);
        FileStreams.acquire(path);

        FileStreams.release(path);
        stream.print("still open");
        stream.flush();
        assertFalse("one holder releasing must not close the stream", stream.checkError());

        FileStreams.release(path);
        stream.print("after the last release");
        stream.flush();
        assertTrue("the last release must close it", stream.checkError());
    }

    @Test
    public void twoLoggersOnOnePathWriteEveryLineWholeAndExactlyOnce() throws Exception {
        File sink = tempFolder.newFile();
        var messageOnly = PatternFormatter.create("%s");

        var first = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        first.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(messageOnly));
        var second = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        second.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(messageOnly));

        int threadsEach = 2;
        int perThread = 500;
        var start = new CountDownLatch(1);
        var workers = new ArrayList<Thread>();
        var expected = new ArrayList<String>();

        var loggers = List.of(first, second);
        for (int l = 0; l < loggers.size(); l++) {
            var log = loggers.get(l);
            for (int t = 0; t < threadsEach; t++) {
                String tag = "logger" + l + "-worker" + t;
                for (int i = 0; i < perThread; i++) {
                    expected.add(line(tag, i));
                }
                var worker = new Thread(() -> {
                    await(start);
                    for (int i = 0; i < perThread; i++) {
                        int n = i;
                        log.info(() -> line(tag, n));
                    }
                }, tag);
                workers.add(worker);
                worker.start();
            }
        }

        start.countDown();
        for (Thread worker : workers) {
            worker.join(10_000);
            assertFalse(worker.getName() + " did not finish", worker.isAlive());
        }
        first.close();
        second.close();

        List<String> written = Files.readAllLines(sink.toPath(), StandardCharsets.UTF_8);
        Collections.sort(expected);
        Collections.sort(written);
        assertEquals("two loggers on one path must not tear each other's lines",
                expected, written);
    }

    @Test
    public void closingOneLoggerLeavesTheFileOpenForTheOther() throws Exception {
        File sink = tempFolder.newFile();
        var messageOnly = PatternFormatter.create("%s");

        var first = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        first.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(messageOnly));
        var second = Logging.create(nextLoggerName(), LogOptions.createFromEnvironment());
        second.changeOptions(to(LogDestination.file(sink.getAbsolutePath())).withFormatter(messageOnly));

        first.info(() -> "from the first");
        first.close();

        // The stream is still held by the second logger, so this must land in
        // the file rather than on the fallback console.
        second.info(() -> "from the second");
        second.close();

        assertEquals("releasing one holder must not close the file under the other",
                List.of("from the first", "from the second"),
                Files.readAllLines(sink.toPath(), StandardCharsets.UTF_8));
    }

    /** Long enough that a torn write would be obvious in the comparison. */
    private static String line(String tag, int i) {
        return tag + "-" + i + "-" + "x".repeat(40);
    }

    private static void await(CountDownLatch latch) {
        try {
            latch.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException(e);
        }
    }

    private static final AtomicInteger LOGGER_SEQ = new AtomicInteger();

    /** Each test gets its own logger name, so the registry never crosses tests. */
    private static String nextLoggerName() {
        return "test.%s".formatted(LOGGER_SEQ.incrementAndGet());
    }
}
